### ISSUE TITLE
Fastfetch makes one tiny error (additional line) in print when not run in terminal start

### ISSUE THREAD

**Issue by tomato4** [LinusDierheimer/fastfetch#101]
When I open new terminal, everything works fine.
![image](https://user-images.githubusercontent.com/26723812/138564196-35154100-9837-49d9-bbb6-b39bd3d63b73.png)

But I have abbreviation for cl = clear; fastfetch. And there it creates one line emtpy and in the end it also creates 1 empty prompt.
![image](https://user-images.githubusercontent.com/26723812/138564253-07ac2373-6a55-4023-9bec-4ee80a7c0e87.png)

(and it's not problem of clear - when I run only fastfetch it does the same thing)
![image](https://user-images.githubusercontent.com/26723812/138564280-df442940-a404-4e68-8eea-c96b965461cb.png)

It's not a big deal. I'm just perfectionist, so it bothers me a little :D
Additional informations about my setup is in the pictures... Or feel free to ask.

Also I tried it on Termite, XTerm, urxvt and it does it in all of these terminals
Also tried Bash instead of Fish and no change. Still does it

**Comment by LinusDierheimer** [comment]
Closing this for now, maybe it gets fixed in future by luck.

**Comment by tomato4** [comment]
Actually it was already fixed by luck, but I forget to report it there. Thanks for the effort.
