### ISSUE TITLE
[Feature request] CentOS support

### ISSUE THREAD

**Issue by CarterLi** [LinusDierheimer/fastfetch#104]
# Current state:

![image](https://user-images.githubusercontent.com/6134068/140301946-e54d42c3-c1fe-4d59-884b-b5862755aaf2.png)

1. No logo
2. No packages count shown ( `/var/lib/rpm/rpmdb.sqlite` doesn't exist )

```
➜  build git:(master) ll /var/lib/rpm/
total 320M
-rw-r--r--. 1 root root  15M Nov  4 18:52 Basenames
-rw-r--r--. 1 root root  24K Nov  4 17:10 Conflictname
-rw-r--r--. 1 root root 344K Nov  4 18:52 __db.001
-rw-r--r--. 1 root root  96K Nov  4 18:52 __db.002
-rw-r--r--. 1 root root 1.3M Nov  4 18:52 __db.003
-rw-r--r--. 1 root root 9.8M Nov  4 18:52 Dirnames
-rw-r--r--. 1 root root  32K Nov  4 18:52 Group
-rw-r--r--. 1 root root  36K Nov  4 18:52 Installtid
-rw-r--r--. 1 root root  92K Nov  4 18:52 Name
-rw-r--r--. 1 root root  44K Nov  4 17:10 Obsoletename
-rw-r--r--. 1 root root 287M Nov  4 18:52 Packages
-rw-r--r--. 1 root root 5.6M Nov  4 18:52 Providename
-rw-r--r--. 1 root root 772K Nov  4 18:52 Requirename
-rw-r--r--. 1 root root 212K Nov  4 18:52 Sha1header
-rw-r--r--. 1 root root 132K Nov  4 18:52 Sigmd5
-rw-r--r--. 1 root root 8.0K Nov  3 17:29 Triggername
```

# Wanted state:

1. Add logo ( maybe use the logo from neofetch https://github.com/dylanaraps/neofetch/blob/222b1cd8d5203966e25a8f365d5ab21649a5fe04/neofetch#L6564 )
2. Find a way to show packages count

# Why the change is sensible:

CentOS and RHEL use are very famous, popular and globally used as server distro. They are even much more popular than Ubuntu Server in my country. As we already supported Fedora, support RHEL should not take too many efforts.

**Comment by CarterLi** [comment]
```
$ rpm --version
RPM version 4.11.3
```

Seems rpm on CentOS 7 still uses the ancient [BDB backend](https://rpm.org/user_doc/db_recovery.html), we should better use the official [RPM API](https://ftp.osuosl.org/pub/rpm/api/4.11.1/annotated.html), which should provide maximum compatibility and should support Fedora too.

**Comment by LinusDierheimer** [comment]
The logo support will definitely come. I'm currently working on rewriting the way logos are loaded, if this is finished, i will implement it. However i just started with university and my time is more limited than before.

I didn't know about the existence of librpm, we should definitely use it over libsqlite3 if possible since it is more reliable and more distributions will be supported. The only point left is how easy it is to get the total package count with it and how fast it is. I will look into it.

**Comment by CarterLi** [comment]
`librpm` works fine on Fedora

![image](https://user-images.githubusercontent.com/6134068/140675470-8860e03b-02c0-4b80-b96d-332f809c1118.png)
