### ISSUE TITLE
An ability to replace distro logo with a picture

### ISSUE THREAD

**Issue by KpauMupa** [LinusDierheimer/fastfetch#108]
# Current state:
Not implemented, i think... Did not find anything relative in the config file.
# Wanted state:
Being able to use any .svg/.png file as a distro logo with the ability 
to change the size of a picture.

This feature is implemented in the neofetch and can be configured in the "# Backend Settings" section of the config file.

**Comment by KpauMupa** [comment]
Referenced feature:
![image](https://user-images.githubusercontent.com/76217453/141650105-a5b5c5eb-adc8-424a-9b1a-647442a76604.png)

**Comment by LinusDierheimer** [comment]
This is planned but not implemented yet, as it is completely terminal depended so a lot of code needs to be written. I will also need to  completely rework the way the logo is printed, currently it is done line by line, with the info in between. This doesn't work when displaying pictures, as they need to be rendered at once. And fastfetch is still in a too early stage to focus on such features. so don't expect it to soon, sorry to disappoint you.

**Comment by LinusDierheimer** [comment]
I now keep track of planned features in DEVELOPMENT.md, as there are too many to use issues for that.
