### ISSUE TITLE
Theme, Icons, Cursor and Fonts aren't supported in the TTY (Dynamic Window Manager)

### ISSUE THREAD

**Issue by KpauMupa** [LinusDierheimer/fastfetch#109]
Output of `fastfetch --version`:
```
fastfetch r469.6cdf32d
```

Output of `fastfetch --load-config devinfo`:
```
Error: couldn't find config: devinfo
```
Output of `fastfetch --load-config devinfo-verbose`:
```
Error: couldn't find config: devinfo-verbose
```

Often helpful questions:
* Does the issue occur across multiple terminal emulators?
* - Yes
* Does the issue occur across multiple shells? 
* - Yes
![image](https://user-images.githubusercontent.com/76217453/141649828-97ad3065-2ba3-4a1b-b5cb-50bbcecbbd4d.png)

**Comment by LinusDierheimer** [comment]
What is the process name of your window manager?

**Comment by LinusDierheimer** [comment]
And is it possible that it doesn't set `XDG_CURRENT_DESKTOP` nor `XDG_SESSION_DESKTOP`?

**Comment by KpauMupa** [comment]
> What is the process name of your window manager?

dwm.

> And is it possible that it doesn't set XDG_CURRENT_DESKTOP nor XDG_SESSION_DESKTOP?
I don't think DWM sets those variables...

**Comment by KpauMupa** [comment]
Regular neofetch does see my font and theme
![image](https://user-images.githubusercontent.com/76217453/141650407-52d8d90e-eda9-4713-a03f-0a88d24631af.png)

**Comment by LinusDierheimer** [comment]
And about the missing configs, copy the content of the `presets` folder to `/usr/share/fastfetch/presets/` or `~/.local/share/fastfetch/presets/`

**Comment by LinusDierheimer** [comment]
Try latest commit.

**Comment by LinusDierheimer** [comment]
Any updates on this?

**Comment by LinusDierheimer** [comment]
Inactive.
