### ISSUE TITLE
Host-format option not working after the updating to the latest version.

### ISSUE THREAD

**Issue by 123-123-nil** [LinusDierheimer/fastfetch#11]
- Input 
`fastfetch --host-format "Skynet" --resolution-format "this works but not host format"`

- output 
![image](https://user-images.githubusercontent.com/64632995/112152888-c5238b00-8c08-11eb-90c2-f5daaed4e43a.png)

- --resolution-format works as intended.unable to change my host as skynet.i tried clean building the package from yay,but it did not help
- Also 
`username@skynet ~> fastfetch --version`
`fastfetch r95.a0af3b0`

- I also tried this but got the same output `fastfetch --host-format {Skynet}{skynet}{skynet} --resolution-format "this works but not host format`

**Comment by LinusDierheimer** [comment]
Should be fixed with latest commit. Feel free to close the issue if it works for you.
