### ISSUE TITLE
Set colours for custom logos

### ISSUE THREAD

**Issue by hmlendea** [LinusDierheimer/fastfetch#117]
# Current state:

There is no way to specify logo colours, if I try to embed the colours in the file, I get the following output:

![image](https://user-images.githubusercontent.com/10261133/146235335-5fef36e2-350c-44ae-ab70-2a7e6765e3c1.png)

# Wanted state:

Either of the following:
 - There is a way to specify the colour of the logo _(akin to the **--color** option for the keys)_
 - The keys would be aligned when a custom logo is used

# Why the change is sensible:

**Comment by hmlendea** [comment]
The script I used just creates the logo file like this:
```bash
echo -e "\e[36;1m ${LINE_TO_PRINT}" >> "${OUTPUT_LOGO}"
```

**Comment by LinusDierheimer** [comment]
I'm actually working on this right now (If you look at DEVELOPMENT.md it is actually the first point). I'm just a bit busy at the moment, but it will definitely come soon.

**Comment by hmlendea** [comment]
Thanks.
Great tool by the way, I'm definetely going to replace neofetch with this one on all my systems once this is supported.

**Comment by LinusDierheimer** [comment]
Both points implemented! 
`fastfetch` now correctly handles color codes in the logo file.

But even better, you can now use the syntax of the internal logos in custom logos too, so you can take full advantage of all the color options available (e.g. `--color-logo false`)

For that use the placeholders `$[1-9]` in your logo file. Use `$$` to print a single `$`. Pass fastfetch `--color-[1-9] <console color code>` to replace the placeholder. Eg `--color-1 35` to have all `$1` replaces with `\033[35m`, aka pink.

If you use `$` in your ascii art and don't want to adjust it accordingly + provide the colors in the file, use `--logo-raw` to bypass all replacements.
