### ISSUE TITLE
No EndeavourOS logo

### ISSUE THREAD

**Issue by Samisafool** [LinusDierheimer/fastfetch#121]
# Current state:

![image](https://user-images.githubusercontent.com/59611020/150324552-3d3231d5-52f4-4dcb-aab3-3d04dbbf4d9b.png)

# Wanted state:

Arch logo replaced with Endeavour logo

# Why the change is sensible:

Because... More distro logos
I wasn't sure whether to file a bug report or feature request, hopefully this is right.

**Comment by LinusDierheimer** [comment]
Implemented, close this if it works for you too.

**Comment by Samisafool** [comment]
Thanks, it works now.

![image](https://user-images.githubusercontent.com/59611020/150329497-fc9c1436-3471-49ea-9207-692e7b77ac61.png)
