### ISSUE TITLE
Misalignment of ArcoLinux Logo

### ISSUE THREAD

**Issue by rdixitv** [LinusDierheimer/fastfetch#126]
Don't know if this is an enhancement of a bug, but I put it here.

Simple problem: The ArcoLinux Ascii art is a little misaligned.

Neofetch
![20220129-145452-arco-neofetch](https://user-images.githubusercontent.com/76796196/151655597-4a294af3-a109-4d7f-91ee-60328734c8e9.png)

Fastfetch
![20220129-145525-arco-fastfetch](https://user-images.githubusercontent.com/76796196/151655602-b119a20f-deeb-4d99-bb41-f897bcaa2fad.png)

**Comment by LinusDierheimer** [comment]
Fixed, thank you for reporting.
