### ISSUE TITLE
Can't find rpm packages or gpu

### ISSUE THREAD

**Issue by spodhuturi16** [LinusDierheimer/fastfetch#128]
Hey thanks for creating this tool, it's pretty awesome! I'm trying to get it up and running on Fedora CoreOS but can't seem to get fastfetch to see my GPU or RPM Packages. Neofetch is able to see these settings but fastfetch isn't. I've tried changing my config file to point to /usr/lib64/librpm.so and that didn't make a difference.Any help would be appreciated
![Screen Shot 2022-02-02 at 1 49 02 PM](https://user-images.githubusercontent.com/62156732/152218287-4490fe98-4ea9-4e37-8390-ef8b50f94e45.jpg)

**Comment by LinusDierheimer** [comment]
Please post the output of the following:
```bash
fastfetch --list-features
```
Did you modify the devinfo preset to show some things above the title? This isn't normal.

**Comment by spodhuturi16** [comment]
`fastfetch --list-features` doesn't return any results. I did edit my config.conf file to display the localip twice just to test out reordering things, but never changed the devinfo preset file.

![Screen Shot 2022-02-03 at 11 21 02 AM](https://user-images.githubusercontent.com/62156732/152383503-d72ef33a-7c7c-4f76-acf0-ff933c6063e9.jpg)

**Comment by LinusDierheimer** [comment]
So your fastfetch was compiled without the support for any shared libraries. If you built manually, you should have seen a lot of warnings, like:
```
CMake Warning at CMakeLists.txt:125 (message):
  Package librpm not found.  Building without support.
```
Even fastfetch doesn't need the library to be present at build nor runtime, it needs the headers at build time. You need to have the according package installed during build time.

Fedora doesn't seem to bundle the headers with the library package. Most probably there is a `-dev`, `-devel` or similar package for each library, e.g. `rpm-devel`.

**Comment by LinusDierheimer** [comment]
Did it work?

**Comment by spodhuturi16** [comment]
I haven't been able to get the librpm-dev package installed on my system due to the immutable filesystem. Going to spin up a normal fedora VM and see if I can compile it on that and port the compiled version over. I'll let you know if I get it working!

**Comment by LinusDierheimer** [comment]
Great! Once you built it, you can use the executable on your core os system too, without needing the libraries.

**Comment by LinusDierheimer** [comment]
If you built with all features, this should be the output of `fastfetch --list-features`:
```
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
xfconf
librpm
```

**Comment by LinusDierheimer** [comment]
Can this be closed?

**Comment by LinusDierheimer** [comment]
Inactive.
