### ISSUE TITLE
[Question] Why isn't everything here just put on neofetch?

### ISSUE THREAD

**Issue by ShawkMusic** [LinusDierheimer/fastfetch#129]
If fastfetch is so much faster then neofetch and they're both open source and MIT licensed, why isn't the code here just put on neofetch? What's the point of an entirely new program to do the same thing but better? Why not just make the original neofetch faster? It's not like there's people out there who specifically need neofetch to be slow

**Comment by hmlendea** [comment]
Because this would require 100% of neofetch's code to be wiped, and replaced with this code.

Neofetch is written in bash, fastfetch is written in C.

**Comment by LinusDierheimer** [comment]
A second point is, that fastfetch and neofetch target a different set of machines. Fastfetch targets only Linux Systems, so i can make use of a lot of linux specific features to achieve the speed fastfetch has. Neofetch also supports MacOS, Windows and a lot of other different systems. If you wanted fastfetch to also support those systems, you basically would have to rewrite the hole thing from scratch.
