### ISSUE TITLE
disable module(s) in config file

### ISSUE THREAD

**Issue by RedCommand** [LinusDierheimer/fastfetch#133]
# Current state:
I don't find any option to disable module(s) from config file

# Wanted state:
Possibility to disable module(s) from config file
I this is already possible maybe write it in the readme

# Why the change is sensible:
I think is can be a pretty cool feature. You say in at the end of the readme that it meant to be put in .bashrc (or other, fish config in my case) to have a pretty welcome message at the shell start, but I wanted a more minimalist things than the complete neofetch prompt. In the case where you compile fastfetch, this is not a problem because the src/fastfetch.c is realy simple to edit but if you install it directly (with the AUR on archlinux in my case) you can not modify the source code.

Ps: Sorry about my bad English

**Comment by Samisafool** [comment]
You can put `--structure <Module you want here>:<another module>`

**Comment by LinusDierheimer** [comment]
You can get all modules your version supports by running `fastfetch --list-modules`. 
The default structure can be obtained by running `fastfetch --print-structure`. 
Customize it to your liking, like Sam said!

**Comment by RedCommand** [comment]
Thanks a lot
