### ISSUE TITLE
Time module

### ISSUE THREAD

**Issue by Samisafool** [LinusDierheimer/fastfetch#134]
# Current state:
There is currently no way to display time
# Wanted state:
There's a time module
# Why the change is sensible:
Because it allows you to see the time whenever you start up the terminal. This would be pretty nice, but idk if it would cause possible slowdowns.

**Comment by LinusDierheimer** [comment]
Time module is not a bad idea, and seems relatively easy to implement. However, these leads to the question, on how to display date. Following options
* Have a separate Date and Time module, give both access to date and time, but only display date / time.
* Have a single module with access to both date and time, display both, name it something like DateTime, Date, or Time.

What do you think is better?

**Comment by LinusDierheimer** [comment]
So a `Date`, `Time` and `DateTime` module. What do you mean with the format from DE? Something related to Desktop Environment, or an output formatted like german time / date?

**Comment by Samisafool** [comment]
> What do you mean with the format from DE

Sorry, I meant like language settings

21/2/2022 for one country, 2/21/22 for another, time is 24 hour for one country, 12 hour for other.

**Comment by LinusDierheimer** [comment]
I think we should stick with the english format as default, as the whole output of fastfetch is english. OC this will be easy to change using format strings.
I can also write a presets for common formats, so one can change it using something like `--load-config time-12`

**Comment by Samisafool** [comment]
Maybe use ISO format?

https://en.wikipedia.org/wiki/ISO_8601

**Comment by LinusDierheimer** [comment]
Implemented, can you please test it? Sorry it took so long, i am a bit busy with university right now.

**Comment by Samisafool** [comment]
Looks good, but can the DateTime module display `Date and Time` or `Date & Time` instead of `Date Time` by default? It looks a bit ugly tbh

**Comment by LinusDierheimer** [comment]
Ofc
