### ISSUE TITLE
GLIBC error

### ISSUE THREAD

**Issue by AloneER0** [LinusDierheimer/fastfetch#137]
./fastfetch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./fastfetch)
./fastfetch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./fastfetch)

i use Bedrock Linux and KDE Neon as my init and i get GLIBC errors it works on gentoo and artix

**Comment by LinusDierheimer** [comment]
You need to compile fastfetch with the lowest version of glibc, that you will use fastfetch with. I don't know exactly how bedrock works, but i suspect that the distribution you compiled on, ships a newer version of glibc than KDE neon.

**Comment by AloneER0** [comment]
KDE Neon is based on Ubuntu LTS so yeah glibc is older

**Comment by LinusDierheimer** [comment]
Then the best way would be to compile on KDE neon and use that binary in gentoo / artix.

**Comment by LinusDierheimer** [comment]
Can this be closed?
