### ISSUE TITLE
Add Zorin OS logo

### ISSUE THREAD

**Issue by gaiserik** [LinusDierheimer/fastfetch#139]
# Current state:
![Capture d’écran de 2022-03-01 20-59-18](https://user-images.githubusercontent.com/19627971/156241334-aa574eb8-dfde-4180-849c-18c85d8eb289.png)
# Wanted state:
Zorin logo instead Ubuntu
# Why the change is sensible:
For the pleasure of Zorin OS users ;)

Thanks.

**Comment by LinusDierheimer** [comment]
Done.
