### ISSUE TITLE
Add a "KDE Neon" Logo to FastFetch

### ISSUE THREAD

**Issue by Danik2343** [LinusDierheimer/fastfetch#141]
# Current state: fastfetch on "KDE Neon" show Linux "Tux" logo

# Wanted state: fastfetch on "KDE Neon" show "KDE Neon" logo

# Why the change is sensible: Updating/Adding Fastfetch logos

**Comment by LinusDierheimer** [comment]
Can you please post the content of you `/etc/os-release`?

**Comment by LinusDierheimer** [comment]
Should work, close this if you can confirm.

**Comment by luni3359** [comment]
It works
