### ISSUE TITLE
[Feature Request]: Releases 

### ISSUE THREAD

**Issue by ThamognyaKodi** [LinusDierheimer/fastfetch#142]
# Current state:

Currently there are no releases in the releases tab.

# Wanted state:

I would like there to be a few releases in the releases tab that contain stable versions of the source code.

# Why the change is sensible:

Well it would allow firstly a easier Gentoo ebuilds (although there are loop arounds) as I am trying to submit an ebuild into the main Gentoo overlay, and also would make it for users to find a stable version. Also I hope the naming system would be easy to understand like `0.0.1`, `2.3.2` or etc. this would make it easier for Gentoo ebuilds but also other distro's package creations rather than depending on the git version.

**Comment by LinusDierheimer** [comment]
I am planning to do releases, but tbh i don't know exactly when.  Ofc i will follow semver for it.
The major version will stay the same for the foreseeable future, and i will create a new minor version for every new feature.

The problem is, it's hard to tell when the code is "stable", because in this software, bugs usually only occur on specific setups, and i want to avoid having to do a new release every second commit or so (for the patch version).

**Comment by ThamognyaKodi** [comment]
Firstly thank you for the response,

I definitely see that side of the issue, which is that there are bugs that occur on specific setups and commits. 

~~But looping back the commit part of that statement, would you say there are some particularly stable commits for the amd64 structure. I know that might a bit hard to say a proper commit just by looking, but do you have any recommendations.~~

Scrap that idea, I see that your commits show that you are trying to work on the first release so I will leave you to it. 

Thank you for considering this issue. I will keep it open for the time being, but will close it a bit after the first release. 

Signed-off-by: Thamognya Kodi <contact@thamognya.com>

**Comment by LinusDierheimer** [comment]
Automatic releases finally work! (I hope i don't have to touch github actions again in the next time). Whenever i bump the version in CMakeLists.txt and push, a new release will be created. I can't tell you now how often this will happen, but probably every second commit or so. Sorry for that, but i don't want anybody to miss out on something.

**Comment by Samisafool** [comment]
What about a fastfetch package on the AUR?

**Comment by LinusDierheimer** [comment]
https://aur.archlinux.org/packages/fastfetch-git

**Comment by Samisafool** [comment]
No, like one that's synced with the releases. Like every other package in existence

**Comment by LinusDierheimer** [comment]
I am not sure if this can be automated, and i don't have the time to do it manually
