### ISSUE TITLE
OpenSUSE logo

### ISSUE THREAD

**Issue by Samisafool** [LinusDierheimer/fastfetch#143]
# Current state:
No OpenSUSE logo
# Wanted state:
*title*
# Why the change is sensible:

**Comment by LinusDierheimer** [comment]
I didn't know which of them you meant, so i just added them all.

**Comment by Samisafool** [comment]
How do you even get those? By hand? A program?

Btw, this is the 69th closed issue, nice!

**Comment by LinusDierheimer** [comment]
The ones i added are mostly stolen from neofetch with a few hand made corrections. The other half i got from pull requests. And yes, nice!
