### ISSUE TITLE
[Feature Request]: Fallback entries

### ISSUE THREAD

**Issue by vypxl** [LinusDierheimer/fastfetch#144]
# Current state:
When some info fails to detect, its line is hidden from the output. `--show-errors` shows the line, and a message containing what failed.

# Wanted state:
It would be nice if we could specify something like `--<entry>-fallback <string>`, such that `<string>` is shown instead of the detected info when the detection fails.

Example `fastfetch --host-fallback "Custom built"` => `... Host: Custom build...`

# Why the change is sensible:
This way, the same config could be used on different machines with differing available info. For example, a laptop might have a battery, but a desktop pc does not. In that case, fastfetch could fall back to `Battery: Plugged in` instead of hiding the line, potentially destroying symmetry.

**Comment by LinusDierheimer** [comment]
For the short term, this is already possible (but laborious) using format strings. The ones for your examples (Host and Battery) would be:
* `{/e}{2} {3}{-}{/}Custom Build`
* `{/e}{4}% [{5}]{-}{/}Plugged in`

In the long term, i will look into a solution for this.

**Comment by LinusDierheimer** [comment]
After all this time, i finally present you `--<module>-error`! Setting it will cause the set text to appear as a fallback, if an error occurred. Note that the format strings above won't work anymore, since normal output and error now use different format strings.
