### ISSUE TITLE
Nix/NixOS support?

### ISSUE THREAD

**Issue by AloneER0** [LinusDierheimer/fastfetch#147]
# Current state: 
fastfetch doesn't detect Nix.

# Wanted state:
Fastfetch could show nix alongside the package manager provided by the distro like neofetch does.

# Why the change is sensible:
Maybe it's not a really important feature but I'm sure some people including me would appreciate Nix support.

**Comment by Samisafool** [comment]
`# sudo pacman -S nix` fyi

**Comment by LinusDierheimer** [comment]
I know about that package, but i don't want to use it, because i am pretty sure using two package managers parallel will brick my system. And i can't develop / test package detection, without having packages installed.

**Comment by Samisafool** [comment]
> because i am pretty sure using two package managers parallel will brick my system

nix is self contained, it is completely safe to use alongside pacman. (It has it's own PATH directory)

**Comment by LinusDierheimer** [comment]
Thanks for pointing it out, i implemented support for it and my system still works!

The bad news is, that i didn't found any way to get package count than to open two `nix-store` processes. If you have any idea how this can be done more efficient, please help me.

**Comment by LinusDierheimer** [comment]
If you are happy with the way the support is, feel free to close this.

**Comment by AloneER0** [comment]
you can install nix alongside pacman with the install script from nixos.org
