### ISSUE TITLE
Deb package is broken

### ISSUE THREAD

**Issue by AloneER0** [LinusDierheimer/fastfetch#149]
Apt crashes when trying to install the deb package dpkg shows the error ```dpkg: error processing archive fastfetch.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 24 package 'fastfetch':
 'Recommends' field, missing package name, or garbage where package name expected
Errors were encountered while processing:
 fastfetch.deb```

**Comment by AloneER0** [comment]
Nope ```dpkg: error processing archive fastfetch-1.3.1-Linux.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 9 package 'fastfetch':
 'Recommends' field, syntax error after reference to package 'libpci3'
Errors were encountered while processing:
 fastfetch-1.3.1-Linux.deb
```
still crashes and dpkg shows this

**Comment by AloneER0** [comment]
``Recommends: libpci3 libvulkan1 libwayland-client0 libxcb-randr0 xcb libxrandr2 libx11-6 libdconf1 libglib2.0-0 libdbus-1-3 libxfconf-0-3 libmagickcore-6.q16hdri-6 libmagickcore-6.q16-6 zlib1g`` this line has a syntax error somewhere after libpci3

**Comment by AloneER0** [comment]
Ok i fixed the syntax error ``Recommends: libpci3, libvulkan1, libwayland-client0, libxcb-randr0, xcb, libxrandr2, libx11-6, libdconf1, libglib2.0-0, libdbus-1-3, libxfconf-0-3, libmagickcore-6.q16hdri-6, libmagickcore-6.q16-6, zlib1g``

**Comment by AloneER0** [comment]
i fixed the deb

**Comment by Samisafool** [comment]
https://github.com/LinusDierheimer/fastfetch/blob/master/CMakeLists.txt#L446=

This block should be the offending one

**Comment by LinusDierheimer** [comment]
Thanks to all of you, i am pretty sure it is fixed in 1.3.2

**Comment by LinusDierheimer** [comment]
1.3.3 works in my ubuntu VM
