### ISSUE TITLE
Add a "Deepin" Logo to FastFetch

### ISSUE THREAD

**Issue by Danik2343** [LinusDierheimer/fastfetch#152]
# Current state:f astfetch on "Deepin" not showing logo

# Wanted state:f astfetch on "Deepin" show "Deepin" logo

# Why the change is sensible: Updating Fastfetch Logos
P.S Deepin logo on neofetch
![image](https://user-images.githubusercontent.com/38865696/165000909-ceccadd9-aafa-4204-842e-2614594149d4.png)

**Comment by LinusDierheimer** [comment]
Again, the `/etc/os-release` file of deepin would be really helpfull

**Comment by LinusDierheimer** [comment]
Done. If it doesn't work, ill need the content of `/etc/os-release`.

**Comment by LinusDierheimer** [comment]
I consider this one closed
