### ISSUE TITLE
Redstar OS logo

### ISSUE THREAD

**Issue by Samisafool** [LinusDierheimer/fastfetch#155]
# Current state:
No redstar os logo
# Wanted state:
Yes redstar os logo
# Why the change is sensible:
- Feature parity with neofetch
![image](https://user-images.githubusercontent.com/59611020/166717318-2a41a2f4-9452-4b0e-b64e-46cc94428717.png)
- Bloat
- Extra code and cruft
- RedStar OS users are a majority of desktop Linux users [citation needed]
- Why not?

**Comment by LinusDierheimer** [comment]
Did id for the [meme](https://www.reddit.com/r/linuxmemes/comments/ui59ps/redstarosfetch/?utm_source=share&utm_medium=web2x&context=3)

**Comment by luni3359** [comment]
Thank you for adding this, now my life is complete.
