### ISSUE TITLE
Uptime shows extra comma if 0 mins

### ISSUE THREAD

**Issue by Samisafool** [LinusDierheimer/fastfetch#159]
Output of `fastfetch --version`:
```
fastfetch 1.3.4-12
```

![image](https://user-images.githubusercontent.com/59611020/168213852-90d81b79-7bb9-497e-a6be-df3806fb570b.png)

Often helpful questions:
* Does the issue occur across multiple terminal emulators?
Yes
* Does the issue occur across multiple shells? (bash, zsh, fish, etc)
Yes

**Comment by LinusDierheimer** [comment]
Fixed, thanks for reporting
