### ISSUE TITLE
Please Add Lines to Show: Devices ++ OpenGL Version || Vulkan Version || OpenCL Version 

### ISSUE THREAD

**Issue by iamhumanipromise** [LinusDierheimer/fastfetch#162]
# Current state: Does not exist 

# Wanted state: For the functionality to exist 

# Why the change is sensible: 

If one wishes to brag with fastfetch and post screenshots on Reddit, Imgur or Discord they must to a fancy combination of fastfetch && glxinfo && vulkaninfo && clinfo with a lot of | grep usage in order to display just the desired information. 

Ideally the lines that could theoretically be useful for bragging rights... would be used for troubleshooting.  "Fastfetch" could quickly determine if all the opencl and vulkan and opengl devices in a system are being detected! Would add to the use-case for fastfetch. 

(perhaps one could use a flag such as fastfetch -m or --minimal for the "classic" output || or one could use fastfetch -g  or --gpu for the extended compute information) 

- OpenGL Core Version: 
- OpenGL Video Memory: 
- OpenGL Device: 
- Vulkan Driver Name: 
- Vulkan Conformance Version
- Vulkan API Version: 
- OpenCL Device Name: 
- OpenCL Device Type: 
- OpenCL Device Version: 
- OpenCL C Version: 
- OpenCL Max Clock Frequency: 
- OpenCL Max Compute Units: 
- OpenCL Max Memory Allocation:

**Comment by LinusDierheimer** [comment]
Would something like this be ok:
```
Vulkan: amdgpu (driver), 1.3 (API version), ...
OpenGL: 4.6 (core version), RX5600M (device), ...
...
```
or do you need an extra module for every key value pair? 
I want to avoid flooding the modules.

**Comment by iamhumanipromise** [comment]
Ah yes, that does seem like a better solution indeed! 

Looks like a great plan!! “Keep it simple”! 

One for OpenCL, one for OpenGL, one for Vulkan. Whoo hoo!

**Comment by LinusDierheimer** [comment]
Great. I will finish 1.4, and then do 1.5, which will contain the requested modules. But be aware that this may take a short amount of time, as i am very busy with university at the moment.

**Comment by iamhumanipromise** [comment]
Take your time: education must remain a priority (along with health, wellness, and fitness of course)!

**Comment by LinusDierheimer** [comment]
All 3 modules now have a basic implementation. Can you please test them and give feedback? 

To use them, add `vulkan`, `opengl` and `opencl` to your structure.

They detect a bit more than shown by default, so look at their format string arguments too, e.g. `fastfetch --help opengl-format`.
