### ISSUE TITLE
Bedrock support

### ISSUE THREAD

**Issue by AloneER0** [LinusDierheimer/fastfetch#165]
# Current state:
fastfetch shows the *hijack* distro fetch info/logo

# Wanted state:
```
--------------------------------------   alone@arcobox 
--------------------------------------   ------------- 
--------------------------------------   OS: Bedrock Linux 
---\\\\\\\\\\\\-----------------------   Kernel: 5.17.9-zen1-1-zen 
----\\\      \\\----------------------   Uptime: 42 mins 
-----\\\      \\\---------------------   Packages: 1344 (pacman), 237 (dpkg) 
------\\\      \\\\\\\\\\\\\\\\\------   Shell: bash 5.1.16 
-------\\\                    \\\-----   Resolution: 1920x1080 
--------\\\                    \\\----   WM: bspwm 
---------\\\        ______      \\\---   Theme: Mountain [GTK2/3] 
----------\\\                   ///---   Icons: Mountain [GTK2/3] 
-----------\\\                 ///----   Terminal: kitty 
------------\\\               ///-----   Terminal Font: Iosevka Nerd Font 13.0 
-------------\\\////////////////------   CPU: Intel i5-4200M (4) @ 3.100GHz 
--------------------------------------   GPU: NVIDIA GeForce GT 755M 
--------------------------------------   GPU: Intel 4th Gen Core Processor 
--------------------------------------   Memory: 2678MiB / 7859MiB (34%) 
```
fastfetch could show bedrock logo and multiple package managers.

# Why the change is sensible:
It would be very cool to have Bedrock support :wink: although you don't have to add it it's your decision

**Comment by LinusDierheimer** [comment]
I try to do it without a VM right now, as this is definitely a feature missing. Can't promise how well this will work out though.

**Comment by LinusDierheimer** [comment]
Should work now, can you please test it?

**Comment by AloneER0** [comment]
Sure

**Comment by AloneER0** [comment]
Logo works only pacman shows up and nix

**Comment by AloneER0** [comment]
Oh then i guess the issue my color scheme

**Comment by LinusDierheimer** [comment]
No, i set a color which doesn't exist, so it used white, which is the default color on my system, but probably not on your. Now i explicitly set white.

**Comment by AloneER0** [comment]
oh

**Comment by AloneER0** [comment]
``/bedrock/strata/<debian,ubuntu,devuan>/var/lib/dpkg/status``

**Comment by AloneER0** [comment]
The location didn't change much the only thing that changed is that it's located in ``/bedrock/strata/<distro>/``

**Comment by LinusDierheimer** [comment]
Does it make sense to iterate over every folder in /bedrock/strata and do the package detection code there?

**Comment by AloneER0** [comment]
Well i don't think there is another way

**Comment by AloneER0** [comment]
It's the *fastest* way i can think of neofetch probably uses ``apt list --installed | wc -l`` but it's way too slow and it breaks the point of fastfetch

**Comment by LinusDierheimer** [comment]
neofetch runs this code in every strata dir

**Comment by AloneER0** [comment]
neofetch checks if apt/dpkg is available if not it doesn't run it

**Comment by AloneER0** [comment]
it doesn't check every strata directory it only uses the package manager to check how many packages are installed

**Comment by LinusDierheimer** [comment]
It overwrites `tot` on bedrock linux

**Comment by AloneER0** [comment]
Hm :thinking:

**Comment by LinusDierheimer** [comment]
Finally found the time to implement package support. Can you please test it?

**Comment by LinusDierheimer** [comment]
Should be working again

**Comment by LinusDierheimer** [comment]
Even after a run with `--recache`?

**Comment by AloneER0** [comment]
Ah after ``-recache`` shows Bedrock!

**Comment by AloneER0** [comment]
Can be closed
