### ISSUE TITLE
Option to disable color codes

### ISSUE THREAD

**Issue by thingsiplay** [LinusDierheimer/fastfetch#167]
# Current state:

Output contains color codes.

# Wanted state:

Option to disable color codes.

# Why the change is sensible:

Redirecting the output of `fastfetch > mysystem.txt` will still include the color codes, which is not useful. Also probably some programs who don't understand color codes wouldn't work with piping.

**Comment by LinusDierheimer** [comment]
It would be a simple thing to disable color codes, but fastfetch uses some other codes too, which are needed to place everything correct. E.g. it prints the logo first, than goes up to the first row, then to the upper left corner. Then it goes to the right for each output line. So fastfetch will never look correctly when viewed with something else than a terminal emulator.

**Comment by thingsiplay** [comment]
Okay, so I have a workaround to remove the color codes then. It is a naive way of doing it, but at the moment I have no better idea: 

    fastfetch --logo none --logo-padding 0 --color 0 | sed -E 's/^[\[[0-9]+(;[0-9])*m//g' | grep -E ':' > output.txt

**Comment by thingsiplay** [comment]
Okay, so I am going with a `sed` command stripping out the color codes saved as `nc` (for nocolor):

    sed -E 's/\x1B\[[0-9;]*[JKmsu]//g'

and combine it like this:

    fastfetch --logo none --logo-padding 0 | nc | grep ': '

**Comment by thingsiplay** [comment]
Okay, so I am going with a `sed` command stripping out the color codes saved as `nc` (for nocolor). And then combine it with any command.

`nc`:

    sed -E 's/\x1B\[[0-9;]*[JKmsu]//g'

and combine it like this:

    fastfetch --logo none --logo-padding 0 | nc | grep ': '

**Comment by LinusDierheimer** [comment]
Currently working on a `--pipe``option, the restriction is that it will force none logo.

**Comment by LinusDierheimer** [comment]
It is pushed, please try it.

**Comment by thingsiplay** [comment]
Wow amazing! This was very fast. I just cloned and build it. It works perfectly as expected. Thank you, this makes it easy to copy to clipboard for sharing online easier. If you need anything tested, tell me. For me it works fine. :-)

**Comment by LinusDierheimer** [comment]
Glad to here that.
