### ISSUE TITLE
Potentially incorrect clock rate

### ISSUE THREAD

**Issue by kojq** [LinusDierheimer/fastfetch#171]
# General description of bug:
Clock rate is displayed as 2GHz when it is 2.1GHz.

* Does the issue occur across multiple terminal emulators? [Y/N]

Yes.

Output of `fastfetch --version`:
```
1.5.3
```

Output of `fastfetch --list-features`:
```
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
```

**Comment by LinusDierheimer** [comment]
What is the output of `cat /sys/devices/system/cpu/cpufreq/policy0/bios_limit`?

**Comment by kojq** [comment]
Yes.

**Comment by LinusDierheimer** [comment]
And does `/sys/devices/system/cpu/cpu0/cpufreq/bios_limit` exist and contain a valid value?

**Comment by LinusDierheimer** [comment]
So it is hard to detect 2.1, if every value the kernel exposes is 2. Maybe something is wrong with your bios configuration.

**Comment by kojq** [comment]
The second comment here was able to display 2.1. What could be wrong with the bios configuration?

**Comment by LinusDierheimer** [comment]
Ah if the file says 2.1, and fastfetch says 1, something is wrong with my parsing. I will look into it.

**Comment by kojq** [comment]
It is 2000000. As far as I can tell, the supposedly "correct" 2.1GHz can only be found under /proc/cpuinfo model name.

**Comment by LinusDierheimer** [comment]
So this is not a bug. I am not going to parse the name to get the frequency, as the kernel doesn't do so either. If the kernel reports 2GHz max, thats the max your CPU is running at, no matter under what name it is marketed.
