### ISSUE TITLE
Improve logo highlighting

### ISSUE THREAD

**Issue by kojq** [LinusDierheimer/fastfetch#187]
When highlighting the logo, the color should, for instance, end at the last character of each line.

**Comment by LinusDierheimer** [comment]
This is actually done by purpose, because most logos are mono color, so this way it is simpler in the most cases. What is the use case for color ending then encountering `\n` for you?

**Comment by LinusDierheimer** [comment]
I considered both options, but came to the conclusion, that overall its less work to design logos, if i leave it as is.
