### ISSUE TITLE
Error: "listener function for opcode 0 of wl_output is NULL" when running on Wayland

### ISSUE THREAD

**Issue by RayJW** [LinusDierheimer/fastfetch#188]
# General description of bug:

In the new version 1.5.5 I run in to this error when running fastfetch on Wayland:
```
listener function for opcode 0 of wl_output is NULL
[1]    23431 IOT instruction (core dumped)  fastfetch --load-config devinfo 
```

# Often helpful questions:
* Does the issue occur across multiple terminal emulators? [Y/N]
Y
* Does the issue occur across multiple shells? (bash, zsh, fish, etc) [Y/N]
Y

Output of `fastfetch --version`:
```
fastfetch 1.5.5
```

Output of `fastfetch --load-config devinfo`:
```
             /////////////                 [REMOVED]@REMOVED]
         /////////////////////             -------------------
      ///////*767////////////////          OS: Pop!_OS 22.04 [x86_64]
    //////7676767676*//////////////        Host: [REMOVED]
   /////76767//7676767//////////////       Kernel: 5.18.8-051808-generic
  /////767676///*76767///////////////      Uptime: 57 mins
 ///////767676///76767.///7676*///////     Packages: 2582 (dpkg), 5 (snap)
/////////767676//76767///767676////////    Shell: zsh 5.8.1
listener function for opcode 0 of wl_output is NULL
[1]    23431 IOT instruction (core dumped)  fastfetch --load-config devinfo
```

Output of `fastfetch --load-config devinfo-verbose`:
```
             /////////////                 [REMOVED]@[REMOVED]
         /////////////////////             -------------------
      ///////*767////////////////          OS: System: Linux; Name: Pop!_OS; Pr4
    //////7676767676*//////////////        Host: Family: "product_family: 103C_P
   /////76767//7676767//////////////       Kernel: Sysname: Linux; Release: 5.12
  /////767676///*76767///////////////      Uptime: Days: 0; Hours: 1; Minutes: 5
 ///////767676///76767.///7676*///////     Processes: Count: 1030
/////////767676//76767///767676////////    Packages: All: 2587; pacman: 0; pacm0
//////////76767676767////76767/////////    Shell: Process name: zsh; Process pa1
listener function for opcode 0 of wl_output is NULL
[1]    33424 IOT instruction (core dumped)  fastfetch --load-config devinfo-vere
```

Output of `fastfetch --list-features`:
```
libpci
vulkan
wayland
xcb
xrandr
x11
gio
dconf
dbus
zlib
xfconf
sqlite3
egl
glx
```

I removed some personal information with [REMOVED] put those things are output as expected. 
The package was installed via Pacstall.

**Comment by LinusDierheimer** [comment]
That is really interesting, because most of my listeners on `wl_output` _are_ `NULL`. According to the wayland docs, they just should never be called.
I will create stub listeners, so this can't happen again.

I have no idea what is different between the pacstall and deb install, if you have any idea please tell me.

**Comment by LinusDierheimer** [comment]
Should be fixed now. But tbh i don't know why the dep package works and the pacstall doesn't. They should contain the same code...

**Comment by RayJW** [comment]
I just checked, and both versions now work as expected again. Sadly, I do not have any further insight on what could be causing the two to behave differently. I'm sorry… but thank you for fixing it :)
