### ISSUE TITLE
Song/Media Player not being detected

### ISSUE THREAD

**Issue by Yureien** [LinusDierheimer/fastfetch#190]
# General description of bug:

Song or media player is not being detected (atleast when using Spotify), although since it works using neofetch, the external parameters (DBus, etc.) probably aren't the issue.

Using NixOS so maybe there's a chance it's not being able to properly read the data?

# Often helpful questions:
* Does the issue occur across multiple terminal emulators? Y
* Does the issue occur across multiple shells? Y (bash/fish)

Output of `fastfetch --version`:
```
fastfetch 1.5.3
```

Output of `fastfetch --list-features`:
```
libpci
vulkan
wayland
xcb-randr
xcb
x11
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
opencl
```

**Comment by Yureien** [comment]
It works if I manually set `LD_LIBRARY_PATH=/path/to/dlib/lib`. This issue only occurs for DBus and not the other libraries, which seem to load fine.

**Comment by Yureien** [comment]
So the problem seems to be how dlopen operates:
```
       o   (ELF only) If the calling object (i.e., the shared library or
           executable from which dlopen() is called) contains a DT_RPATH
           tag, and does not contain a DT_RUNPATH tag, then the
           directories listed in the DT_RPATH tag are searched.

       o   (ELF only) If the calling object contains a DT_RUNPATH tag,
           then the directories listed in that tag are searched.
```

For some reason, this doesn't work with DBus. I've patched the Nix script to instead use `LD_LIBRARY_PATH` which resolves this issue. Seems solved for now.

**Comment by LinusDierheimer** [comment]
Still weird... Will look into this.
