### ISSUE TITLE
Improve detect NixOS version

### ISSUE THREAD

**Issue by Izorkin** [LinusDierheimer/fastfetch#194]
Not showing full version of NixOS:
```
OS: NixOS 22.11 (Raccoon) x86_64
```
Needed this variant:
```
OS: NixOS 22.11.git.31109649164 (Raccoon) x86_64
```

Bash script version:
```
            elif [[ -f /etc/NIXOS ]]; then
                case $distro_shorthand in
                    on) distro="NixOS $(nixos-version | awk '{print substr($1,0,5),$2}')" ;;
                    tiny) distro="NixOS" ;;
                    *) distro="NixOS $(nixos-version)" ;;
                esac
```

**Comment by LinusDierheimer** [comment]
Is there a way to get the full version without executing `nixos-version`?

**Comment by Izorkin** [comment]
Yes, can parse file `/etc/os-release`:
```
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="22.11pre392643.31109649164"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 22.11 (Raccoon)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="22.11 (Raccoon)"
VERSION_CODENAME=raccoon
VERSION_ID="22.11"

```

**Comment by Izorkin** [comment]
@LinusDierheimer found a close match:
```
fastfetch --os-format "{2} {11} {10} {12}"
...
OS: NixOS 22.11.git.31109649164M raccoon x86_64
```
It has an excess letter `M` and displays `raccoon` instead of `(Raccoon)`

**Comment by LinusDierheimer** [comment]
TBH i don't think it is a good idea to show a different version by default, than what the distribution intends (that is, `PRETTY_NAME`).

**Comment by Izorkin** [comment]
Screenfetch displays the full version of the OS. To Neofetch also added a patch to NixOS - https://github.com/NixOS/nixpkgs/pull/181978

**Comment by LinusDierheimer** [comment]
I am happy to implement it then. However, wouldn't it be easier to correct `PRETTY_NAME`? Maybe we should start a merge request for that.

**Comment by Izorkin** [comment]
Add to `/etc/os-release` `FULL_NAME` ?

**Comment by LinusDierheimer** [comment]
No, update `PRETTY_NAME`. Those values are standardized by XDG. `PRETTY_NAME` is what the distribution expects informative programs to show, so i would like to keep fastfetch adheering that spec and just display `PRETTY_NAME`.

**Comment by Izorkin** [comment]
Can't change `PRETTY_NAME`, see - https://github.com/NixOS/nixpkgs/pull/74850

**Comment by Izorkin** [comment]
Or adding an additional line with `OS Build ID`
```
OS: NixOS 22.11 (Raccoon)
OS Build ID: 22.11.git.4199a5fab9d
```
or `Build ID`:
```
OS: NixOS 22.11 (Raccoon)
Build ID: 22.11.git.4199a5fab9d
```

**Comment by LinusDierheimer** [comment]
Can you please test with git master?

**Comment by Izorkin** [comment]
Working!
```
/result/bin/fastfetch --logo none | grep OS
OS: NixOS 22.11.git.4a9de789e1cM (Raccoon) x86_64
```
Thanks!

Does it make sense to  adding an additional line with `OS Build ID` ?

**Comment by LinusDierheimer** [comment]
I don't want to add another module just for build id. Closing this as completed, as it is now visible in the default OS output.
