### ISSUE TITLE
Add global configuration

### ISSUE THREAD

**Issue by Izorkin** [LinusDierheimer/fastfetch#196]
Please add support reading global configiration from file `/etc/.fastfetch` or `/etc/fastfetch/config.conf`.
When running `fasfetch`, it looks for configuration in `/etc/.fastfetch`. If the file is found, then `fastfetch` uses it and does not create the file `~/.config/fastfetch/config.conf`
And add options `--load-config none` (launch without config) and `--no_config` (Don't create the user config file).

I also found an error. Created a configuration file `~/fastfetch.config`
```
--logo nixos_old
--color cyan
--kernel-format {1} {2}
```

and running `fastfetch --load-config ~/fastfetch.config`. 
Option `--color cyan` not working.

**Comment by LinusDierheimer** [comment]
Fastfetch now loads `/etc/fastfetch/config.conf` before loading user configuration or arguments. This file is also now installed by cmake, and therefore included in all future packages. If this file contains `--load-user-config false`, the user config file will not be created / parsed and arguments are ignored. Otherwise values set inside there can be overwritten.

Just for interest, what is the use case for that?

**Comment by LinusDierheimer** [comment]
I cannot reproduce the color error. Maybe cyan and blue look too similar on your system, try passing red for example.

**Comment by Izorkin** [comment]
When I ssh into a remote system, I always start neofetch. Outside of a global build, you must manually configure neofetch each time. Or writing a config file and add in an alias. Uncomfortable to use:
```
{ pkgs, ... }:
let
  neofetchConfig = pkgs.writeText "neofetch.config" ''
    ascii_distro="nixos_old"
    cpu_temp="C"
    image_backend="ascii"
    image_source="ascii"
    memory_percent="on"
    memory_unit="gib"
    title_fqdn="on"
  '';
in {
...
  environment.shellAliases = {
    neofetch = "neofetch --config ${neofetchConfig}";
  };
...
  programs.zsh = {
...
    loginShellInit = "neofetch --config ${neofetchConfig}";
  };
```

If paramer is set `--load-user-config true` or not set, then parameters set in global file are overwritten by local config.
Global config:
```
--logo nixos_old
--color cyan
--kernel-format {1} {2}
```
Local config:
```
--logo nixos
--host-format {2}
```
Result config:
```
--logo nixos
--color cyan
--kernel-format {1} {2}
--host-format {2}
```

**Comment by LinusDierheimer** [comment]
It is expected behaviour, that the global file is overwritten by user config file, as this is the way global config files usually work, and i want to keep it that way. Just set `--load-user-config false`.

**Comment by Izorkin** [comment]
@LinusDierheimer ok)

**Comment by Izorkin** [comment]
With enable in systemv config `--load-user-config false` not working command `fastfetch --help`.

**Comment by LinusDierheimer** [comment]
Thats the point of ignoring arguments.
