### ISSUE TITLE
Confusing ffStrbufTrim behaviour

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#20]
I'm looking into another approach to WM Theme recognition.
ffStrbufTrim seems to behave rather weird. Here's some good old printf debug output:
```
Original string: 		"    <name>Matcha-dark-azul</name>
"
Original strLen: 			34
Post ffStrbufRemoveStringsA strLen 	21
Post ffStrbufTrim strLen 		16
Post ffStrbufRecalculateLength strLen 	20
Resulting string: 		 "MatcMatcha-dark-azul"
```
The line feed is removed, but the leading 4  spaces are not. It seems to shift the string by 4, but not deleting the chars. The correct string length should be 16 as it says post trim. It somehow changes after that.
Here's the relevant section:
```
fStrbufSetS(&themeStrbuf, line);
ffStrbufRemoveStringsA(&themeStrbuf, 2, delStrs);
ffStrbufTrimRight(&themeStrbuf, '\n');
ffStrbufTrim(&themeStrbuf, ' ');
ffStrbufRecalculateLength(&themeStrbuf);
```
Am I missing something?

**Comment by LinusDierheimer** [comment]
Can you post the content of the string after each operation? `ffStrbufPutTo(&themeStrbuf, stdout);` should help. Also how delStrs is declared. 

`ffStrbufRecalculateLength` is not needed, as all strbuf functions always keep the length up to date. I use it only after i let a c function like sscanf write directly in the strbuf buffer.

**Comment by LinusDierheimer** [comment]
Update: ffStrbufTrimLeft actually didn't set the null byte at the end. Since i used only strbuf functions which use the length i never encountered an issue with that. But your call of ffStrbufRecalculateLength found the out dated null byte (before the trim) and therefore resized the strbuf to a wrong size. I fixed it just now to avoid bugs with functions that expect a null terminated string.

**Comment by DarNCelsius** [comment]
```
Original string: 		"    <name>Matcha-dark-azul</name>
"
    Matcha-dark-azul

    Matcha-dark-azul
MatcMatcha-dark-
```
I used recalculate just to see what was happening.
Interestingly, as you can see above, `printf("Resulting string: \t\t %s\n", themeStrbuf.chars);` is producing a different result than `ffStrbufPutTo(&themeStrbuf, stdout);`
They're both wrong though. ;)

**Comment by LinusDierheimer** [comment]
They produce different results as ffStrbufPutTo writes exactly length bytes to the FILE buffer for better performance and printf searches a null byte which was not set.

**Comment by LinusDierheimer** [comment]
ffStrbufTrimRight actually had a major bug i somehow was lucky to never encounter. Fixed with the latest commit.

**Comment by DarNCelsius** [comment]
Indeed it's fixed. GJ.
