### ISSUE TITLE
Incorrect WM information

### ISSUE THREAD

**Issue by kojq** [LinusDierheimer/fastfetch#200]
# General description of bug:

The WM should show as Mutter (Wayland) but shows as gnome-shell (Wayland) on Arch with GNOME 42.3.1.

Output of `fastfetch --version`:
```
1.5.6 and a96f797
```

**Comment by LinusDierheimer** [comment]
What is the output of `ps -p "$(lsof -t "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY:-wayland-0}")" -ho comm=` on your system?

**Comment by LinusDierheimer** [comment]
Hmm. That means that the process, which opened and listens on the wayland socket, is gnome-shell. Is there also a mutter process running, or is it just weirdly named?

**Comment by kojq** [comment]
gnome-shell is a Mutter plugin, so Mutter must be running. I recall Mutter was shown as the WM rather than gnome-shell a few weeks prior.

**Comment by LinusDierheimer** [comment]
Thats likely, as i implemented detection through the socket. Before it iterated through every running process and compared them with a list of known names, which was much slower and only worked for compositors i added to this list. 
Is it safe to say that the compositor is always mutter, when the gnome-shell is running? If yes i can do a simple replacement in code.

**Comment by LinusDierheimer** [comment]
Fixed.
