### ISSUE TITLE
Add option to show FQDN title

### ISSUE THREAD

**Issue by Izorkin** [LinusDierheimer/fastfetch#203]
Please add option `--title_fqdn on/off` to Hide/Show Fully Qualified Domain Name in title.
Example `fastfetch --logo none --title_fqdn on`:
```
user@nixos.example.com
-------------
...
```

**Comment by LinusDierheimer** [comment]
You can try the latest commit with `--title-fqdn`. I don't have a way to test it, but it _should_ work.

**Comment by Izorkin** [comment]
@LinusDierheimer working, thanks!
