### ISSUE TITLE
Make it possible to write longer separator string

### ISSUE THREAD

**Issue by wvlab** [LinusDierheimer/fastfetch#215]
### Current state:
Separator string is only 12 bytes long
![image](https://user-images.githubusercontent.com/89403101/185233812-03edd90b-91ee-448c-ae22-ffc15687cbb6.png)
### Wanted state:
It would be great if program could handle more than 12 bytes or 12 ascii chars
### Why the change is sensible:
Themes, customization.
Neofetch users are customizing it, like [here](https://github.com/chick2d/neofetch-themes/), using unicode characters. Now fastfetch can handle only 3 unicode chars in separator string a time

**Comment by LinusDierheimer** [comment]
The separator is currently always exactly the length of the title (username@host). The type of theming you wan't is currently not possible, but i am working on it.

**Comment by wvlab** [comment]
> The separator is currently always exactly the length of the title (username@host).
So I can modify username@host to be exact same length of separator string, it's an idea

**Comment by LinusDierheimer** [comment]
I did some small changes, and now i am able to recreate the first example you linked, with following config file:
```
--separator "  "
--set-keyless HardwareStart=┌───────── \e[1mHardware Information\e[0m ─────────┐
--set-keyless SoftwareStart=├───────── \e[1mSoftware Information\e[0m ─────────┤
--set-keyless InformationEnd=└────────────────────────────────────────┘
--set-keyless Colors=    \e[38m \e[37m \e[36m \e[35m \e[34m \e[33m \e[32m \e[31m
--structure HardwareStart:Host:CPU:GPU:Memory:Resolution:SoftwareStart:OS:Kernel:WM:Shell:Terminal:TerminalFont:Packages:InformationEnd:Colors
--host-key "  "
--cpu-key "  "
--gpu-key "  ﬙"
--memory-key "  塞"
--resolution-key "  "
--os-key "  "
--kernel-key "  "
--wm-key "  "
--shell-key "  "
--terminal-key "  "
--terminal-font-key "  "
--packages-key "  "
```

Is this sufficient?

**Comment by wvlab** [comment]
It's absolutely awesome, thanks for your job! Best fetch utility I've seen

**Comment by LinusDierheimer** [comment]
If you have a cool theme feel free to open a pull request to add it to `presets/`. This way everybody can access it with a simple `--load-config <your-unique-theme-name>`.

**Comment by Dan1jel** [comment]
> I did some small changes, and now i am able to recreate the first example you linked, with following config file:
> ```
> --separator "  "
> --set-keyless HardwareStart=┌───────── \e[1mHardware Information\e[0m ─────────┐
> --set-keyless SoftwareStart=├───────── \e[1mSoftware Information\e[0m ─────────┤
> --set-keyless InformationEnd=└────────────────────────────────────────┘
> --set-keyless Colors=    \e[38m \e[37m \e[36m \e[35m \e[34m \e[33m \e[32m \e[31m
> --structure HardwareStart:Host:CPU:GPU:Memory:Resolution:SoftwareStart:OS:Kernel:WM:Shell:Terminal:TerminalFont:Packages:InformationEnd:Colors
> --host-key "  "
> --cpu-key "  "
> --gpu-key "  ﬙"
> --memory-key "  塞"
> --resolution-key "  "
> --os-key "  "
> --kernel-key "  "
> --wm-key "  "
> --shell-key "  "
> --terminal-key "  "
> --terminal-font-key "  "
> --packages-key "  "
> ```
> 
> Is this sufficient?

When trying this i get 
```
Error: unknown option: --set-keyless HardwareStart=┌───────── \e[1mHardware Information\e[0m ─────────┐
```
