### ISSUE TITLE
Replace gethostbyname() with getaddrinfo() or getnameinfo()

### ISSUE THREAD

**Issue by jonathanspw** [LinusDierheimer/fastfetch#217]
# Current state:
`gethostbyname()` has long been obsolete and `getaddrinfo()` or `getnameinfo()` should be used instead.

# Wanted state:
Use `getaddrinfo()` or `getnameinfo()` in https://github.com/LinusDierheimer/fastfetch/blob/master/src/detection/title.c#L30

# Why the change is sensible:
`gethostbyname()` has been obsolete for man years.

**Comment by LinusDierheimer** [comment]
Done, thanks for pointing it out.

**Comment by LinusDierheimer** [comment]
Just saw that you are packaging it for fedora, thanks for that! Do you need a point release for that?

**Comment by jonathanspw** [comment]
That was quick, thank you!

I can do a patch for this for now.  I'm pushing it out for Fedora Rawhide (dev branch) but I'm not pushing it to current stable releases or EPEL yet.  Due to update policies we can't really push backwards-incompatible updates to normal/stable branches and since 1.6.x > 1.7.x will have such changes (the config files), I'm waiting for 1.7 to release into those branches of the OS that way hopefully updates won't get blocked by backwards-incompatible changes for a while :)

**Comment by jonathanspw** [comment]
Erm,

I'm mixing up projects.  I'll be pushing this to all stable versions of Fedora/EPEL that it will build on.

**Comment by LinusDierheimer** [comment]
I do a small release than. That way you don't need patches for this or the alma linux logo.

**Comment by jonathanspw** [comment]
Works for me :)

**Comment by jonathanspw** [comment]
It will be going into F35+ and EPEL8/9
