### ISSUE TITLE
Showing RAM in GiB (GB)

### ISSUE THREAD

**Issue by sirlucjan** [LinusDierheimer/fastfetch#218]
# Current state:

The amount of RAM is shown only in MiB

# Wanted state:

Ability to display RAM also in GiB (GB)

# Why the change is sensible:

It would certainly be much more readable for anyone with more than 16 GB of RAM - and that's almost standard now.

**Comment by LinusDierheimer** [comment]
Good idea, implement.

**Comment by sirlucjan** [comment]
Works fine, thanks a lot
![2022-08-23-145139_1920x1080_scrot](https://user-images.githubusercontent.com/5910665/186162768-201be650-9f9f-4e11-bfdc-dbf2c133130f.png)
.
