### ISSUE TITLE
MSYS2 logo

### ISSUE THREAD

**Issue by Danik2343** [LinusDierheimer/fastfetch#219]
# OS
```
paste content of /etc/os-release here. If this file doesn't exist, describe a way to identify the distro.
```
[ascii-art.zip](https://github.com/LinusDierheimer/fastfetch/files/9418578/ascii-art.zip) P.S converted icon to ASCII

# Ascii
```
paste ascii art here. If you leave this empty, i will try to find the logo myself.
```
[os-release.zip](https://github.com/LinusDierheimer/fastfetch/files/9418572/os-release.zip)

**Comment by LinusDierheimer** [comment]
Implemented. I've created a logo by myself, because yours was a bit big, and set the background instead of the text. Feel free to criticize it.
