### ISSUE TITLE
Multiple module output on same line

### ISSUE THREAD

**Issue by Evo112358** [LinusDierheimer/fastfetch#223]
# Current state: 
Current output is limited to one module per line. 
Output can be customised with things added to in plain text or altered it via the {} option, however multiple modules output cannot be combined onto the same line.

Format options from my config as example:
```
--os-format {3}
--terminal-format {1} ->
--shell-format {6}
--wm-format {2} [{3}]
--disk-format {1}/{2}GB [{4}%]
--packages-format [{2}] flatpak [{12}]

```
Output:
```
Arch Linux
alacritty -> 
zsh
Hyprland [Wayland]
322.365/341.789GB [94%]
[514] flatpak [0]
```

# Wanted state:
Combining output whilst allowing users to add custom information.
Format Options combining terminal and shell modules:
```
--os-format {3}
--terminal-format {1} -> --shell-format {6} 
--wm-format {2} [{3}]
--disk-format {1}/{2}GB [{4}%]
--packages-format [{2}] flatpak [{12}]
```
Output:
```
Arch Linux
alacritty -> zsh
Hyprland [Wayland]
322.365/341.789GB [94%]
[514] flatpak [0]
```

# Why the change is sensible:
Offers a greater ability to customise the output with the information provided.

**Comment by LinusDierheimer** [comment]
This is pretty difficult to implement, given the current structure. Would it be enough for you if i expose the shell values to the terminal format string? Internal they are already detected by a common method.

**Comment by Evo112358** [comment]
Yes that should work.
Would it mean that options {1} - {3} are the same terminal-format options and then the shell-format options are tacked on to the end, {1} - {7}, getting shifted over 3 places to start at {4}?
Or would it be a fixed value, using the shells default "{3} {4}" output that can be added onto the teminal-format string as an additional entry?

**Comment by LinusDierheimer** [comment]
Can we close this as won't fix for now, or do you need something else?
