### ISSUE TITLE
Displaying the GPU name ends with ellipsis if it is too long

### ISSUE THREAD

**Issue by kojq** [LinusDierheimer/fastfetch#224]
# Current state:
Displaying the GPU name results in getting cut off with ellipsis if it is too long.

# Wanted state:
The complete GPU name should show.

# Why the change is sensible:
The information is intended to be readable.

**Comment by LinusDierheimer** [comment]
Fastfetch doesn't do this, this is most probably your terminal emulator. Try running with `--disable-linewrap false`

**Comment by luni3359** [comment]
I got the same problem here, here's the results of running it with that line
![Terminal fastfetch screenshot](https://user-images.githubusercontent.com/16832398/189384168-92e8b3af-20ba-42e5-9c03-fcd5fbc12c67.png)
I had the terminal window expanded fullscreen, I just cropped the image.

**Comment by LinusDierheimer** [comment]
I think it was libpci cutting the name, please try latest commit.

**Comment by luni3359** [comment]
It works now. Thank you.
