### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by Danik2343** [LinusDierheimer/fastfetch#228]
# Current state: FreeBSD port not available and not building in FreeBSD

# Wanted state: FreeBSD port available or Fastfetch build for FreeBSD

# Why the change is sensible: Adding support to other OSes

**Comment by LinusDierheimer** [comment]
Will look into this, as soon as i finished exams for this semester. Currently the newly added MacOS support is taking all of the time i have left from learning.

**Comment by LinusDierheimer** [comment]
BSD is now relatively good supported in my VM, can you please test it and give feedback?

**Comment by LinusDierheimer** [comment]
BSD is now fully supported.
