### ISSUE TITLE
It's possible to get battery status on Android with termux-api

### ISSUE THREAD

**Issue by CarterLi** [LinusDierheimer/fastfetch#243]
https://wiki.termux.com/wiki/Termux-battery-status

For reference: https://github.com/termux/termux-api-package/blob/master/termux-api.c#L30

**Comment by CarterLi** [comment]
![c8bb1db42b06824bc9179c5b29dc1e6](https://user-images.githubusercontent.com/6134068/191068534-9df7e212-e41e-4858-aec8-f4eefbf35430.jpg)

Also the icon of Android seems use too much space.

**Comment by LinusDierheimer** [comment]
> https://wiki.termux.com/wiki/Termux-battery-status
>
> For reference: https://github.com/termux/termux-api-package/blob/master/termux-api.c#L30

Perfect, something i can do to procrastinate even more

> Also the icon of Android seems use too much space.

I copied it from neofetch, but never really noticed because i do android development on a tablet with an usb keyboard, so i have a big screen. Maybe use android_small by default?

**Comment by LinusDierheimer** [comment]
On both my android devices, `termux-battery-status` needs at least 7 seconds (!) to finish, so this method is not really practicable for fastfetch...

**Comment by CarterLi** [comment]
It was pretty fast for me

Querying battery status should not take too much time, strange enough

**Comment by LinusDierheimer** [comment]
Clicking through the source code of termux api, i found the implementation [here](https://github.com/termux/termux-api/blob/6e80b07f66a6b959a8b92e91daaf52ac30b371c0/app/src/main/java/com/termux/api/apis/BatteryStatusAPI.java#L24).

It basically waits for a broadcast event of battery status change, so speed is dependent on how often your device updates its battery status. In the worst case this is hardware dependent. I can't find a way to get the current level without waiting for this event...

**Comment by CarterLi** [comment]
That was bad

**Comment by Dan1jel** [comment]
I know this is maybe not optional due to the 7sec. But i tried to find any documentation ok who to enable this (for battery and wifi) but can't find any. My phone only shows "0" and when charging "0%", wifi is not displayed, how do I enable battery and wifi via termux-api, or where can I find documentation about it. Thanks.

**Comment by CarterLi** [comment]
![Screenshot_2023-02-17-17-50-42-328_com.termux.jpg](https://user-images.githubusercontent.com/6134068/219611384-676093dc-2de4-4f52-b945-ce25b7de7ffe.jpg)

Please verify if these two commands work

**Comment by Dan1jel** [comment]
> ![Screenshot_2023-02-17-17-50-42-328_com.termux.jpg](https://user-images.githubusercontent.com/6134068/219611384-676093dc-2de4-4f52-b945-ce25b7de7ffe.jpg)
> 
> Please verify if these two commands work

Yes they work

![Screenshot_20230217-205231.png](https://user-images.githubusercontent.com/4266424/219777636-a92badce-2ede-439e-94c7-18f33903fda1.png)
