### ISSUE TITLE
DConf

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#25]
Would it be possible to add dconf at compile time?
```c
link_libraries(
    ${CMAKE_DL_LIBS}
    Threads::Threads
    dconf
)
```
Idk if this is similar to the libxml issue, but I'm trying to use dconf to read settings for programs that doesn't have config files (Tilix terminal font atm). I've tried to use your code from `detectGTK.c`, but it segfaults at `ffdconf_client_new()` every time. 
Adding the above makes the code work immediately using just `dconf_client_new()`. All the other calls work though.

edit: If this is the same as the libxml2 thing, I'd love some pointers as to why it fails. If I can get this to work, I could probably rewrite the openbox code to use libxml2 instead with dlsym (Openbox depends on libxml2). The current implementation is very fragile.

**Comment by DarNCelsius** [comment]
![segf](https://user-images.githubusercontent.com/82701459/116772242-cf2d7a80-aa4d-11eb-9ed4-370a963ad141.png)

**Comment by DarNCelsius** [comment]
Using -`-multihtreading false` gives this output:
```
(process:1693868): GLib-GObject-WARNING **: 09:11:42.602: cannot register existing type 'DConfClient'

(process:1693868): GLib-CRITICAL **: 09:11:42.603: g_once_init_leave: assertion 'result != 0' failed

(process:1693868): GLib-GObject-CRITICAL **: 09:11:42.603: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```
Could it be threading related?

**Comment by DarNCelsius** [comment]
When disabling the DConf open in `detectGTK.c`, it works. It seems it's not possible to use DConf in other places?

**Comment by DarNCelsius** [comment]
I made a version that puts the dconfclient in `instance->state`, exposing it that way. Works a treat.
I also made a `ffReadDConfSetting()` in `io.c` that makes it easy to access dconf from anywhere (`parseGTKDConfSettings()` uses `instance->state->dclient` in the image below).
Here's the code to detect the terminal font of Tilix:
```c
static void printTilixTerminal(FFinstance* instance)
{
    char font[128];
    font[0] = '\0';

    ffReadDConfSetting(instance, "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/font", font);

    printTerminalFont(instance, font);
}
```
No error checking, but you can see how easy it is to implement other settings this way.

Would you be interested in exposing dconf in some way like this?
![hack](https://user-images.githubusercontent.com/82701459/116783974-0160cb80-aa92-11eb-902c-3674eb3a0712.png)

**Comment by LinusDierheimer** [comment]
I actually just pushed a very similar method, `const char* ffDConfGetValue(FFinstance* instance, const char* key)`. I just store the dcconf stuff in a static object in the function itself to ensure it is loaded only once. Maybe this method fixes both your problems.

**Comment by DarNCelsius** [comment]
Awesome work, Linus. This is exactly what I was thinking!

I'll get to testing. :)

**Comment by DarNCelsius** [comment]
DConf doesn't seem to work at all:
![dconfbug](https://user-images.githubusercontent.com/82701459/116785640-fbbbb380-aa9a-11eb-9c95-fb852024e66f.png)
Does it work on your end?

**Comment by LinusDierheimer** [comment]
Like a charm. Can you trace down which part of the dconf code fails?

**Comment by DarNCelsius** [comment]
Line 18, dconf.c:
```c
    if(dconf->dconfClient == NULL)
        return NULL
```
This evaluates to NULL.

**Comment by LinusDierheimer** [comment]
So most probably it fails somewhere in loading the library or at ffdconf_client_new. Can you look at where the first call to ffDconfGetValue fails?

**Comment by DarNCelsius** [comment]
What do you mean? It fails at the first try. DConf is lost somehow. I can't track it down. There's no DConf  available at all. This is with r196.

**Comment by LinusDierheimer** [comment]
So in the first call it reaches ffdconf_client_new and this doesn't return NULL?

**Comment by DarNCelsius** [comment]
Yes. This is the state at line 82:
![dconfbug2](https://user-images.githubusercontent.com/82701459/116786808-07aa7400-aaa1-11eb-9157-ec5385a7d6f2.png)

**Comment by LinusDierheimer** [comment]
Found the bug and fixed it. I don't even know why it worked before on my side.

**Comment by DarNCelsius** [comment]
r198:
![dconfbug3](https://user-images.githubusercontent.com/82701459/116787046-36751a00-aaa2-11eb-8581-99a50026aea8.png)

**Comment by LinusDierheimer** [comment]
You were 5 seconds to early, pull again.

**Comment by DarNCelsius** [comment]
Yess

**Comment by LinusDierheimer** [comment]
So this can be closed?

**Comment by DarNCelsius** [comment]
It works like a charm. :D
![dconfbugfixed](https://user-images.githubusercontent.com/82701459/116787229-5953fe00-aaa3-11eb-9586-f62ea52dfbea.png)

**Comment by DarNCelsius** [comment]
Small request - could you implement [dconf_client_read_full()](https://developer.gnome.org/dconf/unstable/DConfClient.html#dconf-client-read-full) as well?
It's required to get the default value when the user hasn't specifically set a setting.

**Comment by LinusDierheimer** [comment]
I've updated `ffDConfgetValue`, now it should fallback to default values. Is this implementation sufficient for your use case?

**Comment by DarNCelsius** [comment]
It looks to be good, but DConf seems broken. Default values are not being read from dconf or fastfetch.

Default read:
![dconfdef](https://user-images.githubusercontent.com/82701459/116802442-06b22a80-ab13-11eb-9795-92e3706d8796.png)

User read:
![dconfuser](https://user-images.githubusercontent.com/82701459/116802448-17fb3700-ab13-11eb-9689-06ccc5b20703.png)

DConf editor seems to pick up default values just fine, so I don't know what's happening.
I might need to look into gsettings/schemas...

**Comment by LinusDierheimer** [comment]
Maybe looking at the source code of your dconf editor will help to understand what we are doing wrong

**Comment by DarNCelsius** [comment]
I'll take a peek:
[DConf Editor](https://github.com/GNOME/dconf-editor)

**Comment by LinusDierheimer** [comment]
I replaced the dconf method with `const char* ffGSettingsGetValue(FFinstance* instance, const char* schema, const char* key)`. This method _should_ always return the best value. Use `schema` and `key` like on the command line with `gsettings`. Example:
```c
themeName = ffGSettingsGetValue(instance, "org.gnome.desktop.interface", "gtk-theme");
iconsName = ffGSettingsGetValue(instance, "org.gnome.desktop.interface", "icon-theme");
fontName = ffGSettingsGetValue(instance, "org.gnome.desktop.interface", "font-name");
```
It querys properties in the following order:
* gsettings value
* gsettings user value
* gsettings default value
* dconf value
* dconf user value
* dconf default value

Hope it helps.

**Comment by DarNCelsius** [comment]
Amazing. You're like a machine man. :1st_place_medal: 

I'll go find the bugs. :face_with_thermometer:

**Comment by DarNCelsius** [comment]
> Schema “com.gexperts.Tilix.Profile” is relocatable (path must be specified)

Does the code support relocatable schemas? Here's the command line to get the default value of the Tilix Terminal font:
`gsettings get com.gexperts.Tilix.Profile:/default/ font`
```
Usage:
  gsettings [--schemadir SCHEMADIR] get SCHEMA[:PATH] KEY

Get the value of KEY

Arguments:
  SCHEMADIR A directory to search for additional schemas
  SCHEMA    The name of the schema
  PATH      The path, for relocatable schemas
  KEY       The key within the schema

```

**Comment by LinusDierheimer** [comment]
To be honest i have no idea. Just try it.

**Comment by DarNCelsius** [comment]
I've tried multiple ways - I wouldn't bother you needlessly if I can help it. One possibility is that the path is the third argument here:

```c
GSettings* settings = data->ffg_settings_new_full(schema, NULL, NULL);
```
This may be used though:
```c
g_settings_new_with_path ()

GSettings *
g_settings_new_with_path (const gchar *schema_id,
                          const gchar *path);

Creates a new GSettings object with the relocatable schema specified by schema_id and a given path.
```
So the schema is `“com.gexperts.Tilix.Profile”`, and the path is `"/default/`. That's where all the default settings are located.
The same procedure also goes for any other profile access.

**Comment by LinusDierheimer** [comment]
I pushed a `const char* ffGSettingsGetValuePath(FFinstance* instance, const char* schemaName, const char* path, const char* key)`. This should help.

**Comment by DarNCelsius** [comment]
That did the trick.
`fontName = ffGSettingsGetValuePath(instance, key.chars, "/default/", "font");`
![termfont](https://user-images.githubusercontent.com/82701459/116824721-f722f800-ab8b-11eb-981d-d3d5e06457b1.png)

**Comment by DarNCelsius** [comment]
I'll close this and leave you alone for a while. Thank you for the work. I have no idea how do all this so fast. :D

**Comment by LinusDierheimer** [comment]
Just for personal interest, are the `/` around `/default/` needed? Would change how i transform the key if i convert it to dconf.

**Comment by DarNCelsius** [comment]
Yes they're needed:
```
(process:455830): GLib-GIO-CRITICAL **: 21:21:34.346: g_settings_new_full: a(process:455830): GLib-GIO-CRITICAL **: 21:21:34.346: g_settings_new_full: assertion 'path == NULL || path_is_valid (path)' failed
                                Terminal Font: Couldn't find "Terminal font" in Tilix settings
```

**Comment by DarNCelsius** [comment]
This is a neverending story...
DConf and GSettings return different results:
```
╭─    ~                                                                                                                                                                                                                                                              ✔  22:21:59  
╰─ dconf read /com/gexperts/Tilix/profiles/687c560b-b486-4c34-92db-d6511072eb2a/font
'Monospace Italic 10'

╭─    ~                                                                                                                                                                                                                                                              ✔  22:22:19  
╰─ gsettings get com.gexperts.Tilix.Profile:/687c560b-b486-4c34-92db-d6511072eb2a/ font
'Monospace 12'
```
DConf and DConf Editor are picking up the user set value. Fastfetch and GSettings seems to return the default one.

**Comment by DarNCelsius** [comment]
Please note the different paths in the above post. I don't think you can just transform '.' into '/' and have it work.

Seems to me it would be better to separate dconf and gsettings functions and have both available globally.
Should make sense performance wise also, as we could opt for using dconf first and fall back to gsettings (dconf being the backend for gsettings).

What do you think?

**Comment by LinusDierheimer** [comment]
Implemented and pushed.

**Comment by DarNCelsius** [comment]
Wow. You don't talk much - I thought I nagged you into a rage with this. Thanks. :D

**Comment by LinusDierheimer** [comment]
Nah i just didn't have free time the last two days
