### ISSUE TITLE
please add fastfetch to brew or other easier way to install fastfetch on macOS

### ISSUE THREAD

**Issue by AWHubGit** [LinusDierheimer/fastfetch#265]
# Current state:
I am unable to install fastfetch on macOS. No installation on macOS 
# Wanted state:
running fastfetch also on macOS
# Why the change is sensible:
allows to install fastfetch easily on macOS

I am running (checking out) fastfetch on arch and Fedora. No problem. I want to install fastfetch on macOS 12.6.
I tried to compile with cmake on macOS. Cmake throws errors that directories/files are not writeable in home-directory and fails with errors.
I downloaded https://github.com/LinusDierheimer/fastfetch/releases/download/1.7.2/fastfetch-1.7.2-Darwin.dmg but can not install as usual as with DMG on macOS. Copying files on command line to /usr/bin and /usr/share not possible with sudo. I think it is the SIP protection preventing this. I am lost now. I am sorry.

I have brew installed on macOS. Please add fastfetch to brew repos. Or add other unspectular method to install fastfetch on macOS.
Thanks
AW

**Comment by LinusDierheimer** [comment]
Will work on that, as soon as i issue the next release. I can't package the current one, because it apparently crashes on Intel macs.

**Comment by LinusDierheimer** [comment]
Should soon be available: https://github.com/Homebrew/homebrew-core/blob/master/Formula/fastfetch.rb

**Comment by AWHubGit** [comment]
fastfetch 1.7.4 works fine now on macOS 12.6 and zsh 5.8.1.
Thanks!
