### ISSUE TITLE
ffSettingsGetDConf not working

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#27]
This code:
```c
        ffStrbufSetS(&key, "/com/gexperts/Tilix/profiles/");
        ffStrbufAppendS(&key, defaultProfile);
        ffStrbufAppendS(&key, "/font");
        puts(key.chars);
        puts("/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/font");

        fontName = ffSettingsGetDConf(instance, key.chars);
        printf("fontName: %s\n", fontName);
```
Produces this:
```
/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/font
/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/font
fontName: (null)
```
My generated string is identical to the one copied from dconf editor. The function returns NULL.

DConf command line:
```
╰─ dconf read /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/font
'Monospace 11'
```

**Comment by LinusDierheimer** [comment]
Which part of the dconf code returns NULL?

**Comment by DarNCelsius** [comment]
Seems to have failed here
![dconfbug4](https://user-images.githubusercontent.com/82701459/117056133-41d37a00-ad1c-11eb-9461-798258e25c65.png)

**Comment by LinusDierheimer** [comment]
Found and solved it. Feeling stupid rn.

**Comment by DarNCelsius** [comment]
That may be a bad spot, this is directly before the call:
![dconfbug5](https://user-images.githubusercontent.com/82701459/117058598-2322b280-ad1f-11eb-9405-269498e7407c.png)

**Comment by LinusDierheimer** [comment]
Close the issue if it works for you too.

**Comment by DarNCelsius** [comment]
It does not:
![dconfbug6](https://user-images.githubusercontent.com/82701459/117059586-40a44c00-ad20-11eb-9fc7-aa178e5ed46d.png)
The library loads now, but the function still fails.

**Comment by LinusDierheimer** [comment]
TBH i dont see what doesnt work in your screenshot

**Comment by DarNCelsius** [comment]
This is immediately after the function call. 'fontName' (top left) is 0x0. I'm having a hard time tracking what's happening in the `getDConfValue` function. Seems to ignore the breakpoints.

**Comment by LinusDierheimer** [comment]
So is fontName == NULL?

**Comment by DarNCelsius** [comment]
Yes

**Comment by LinusDierheimer** [comment]
Can you try with a different hard coded key to ensure it is the function that fails?

**Comment by DarNCelsius** [comment]
Damn. It works. I must have changed the settings trying to fix it. :blush:

**Comment by DarNCelsius** [comment]
I'll just ask here instead of opening another issue; Do you think you could implement more value types?
```
/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/use-system-font

(process:387698): GLib-CRITICAL **: 21:56:07.273: g_variant_get_string: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_STRING) || g_variant_is_of_type (value, G_VARIANT_TYPE_OBJECT_PATH) || g_variant_is_of_type (value, G_VARIANT_TYPE_SIGNATURE)' failed
```
I need at least `bool` to get this working.

**Comment by LinusDierheimer** [comment]
pushed.

**Comment by DarNCelsius** [comment]
I feel like a broken record with this, but could you implement Boolean for DConf as well?
GSettings keep returning the default value despite what the user has configured. DConf gets it right:
![dconfbool](https://user-images.githubusercontent.com/82701459/117529879-7d02d100-afda-11eb-891d-65d2617a89ac.png)

**Comment by DarNCelsius** [comment]
I feel like a broken record with this, but could you implement Boolean for DConf as well?
GSettings/Fastfetch keep returning the default value despite what the user has configured. DConf gets it right:
![dconfbool](https://user-images.githubusercontent.com/82701459/117533909-76cb1f80-afef-11eb-9d4b-973e007a9c93.png)
I can use the NULL result from DConf if the value is not set as an indicator of using the default (True in this case).

**Comment by LinusDierheimer** [comment]
I feel like my implementation has a bug somewhere if we are getting that many bugs. Maybe you could take the time to look into it?

**Comment by DarNCelsius** [comment]
I've tested this all day.

I think GSettings itself is broken when using relocatable schemas. I can toggle something like `org.cinnamon desktop-effects`, and get the correct value. Anything that uses a "Schema with path" works, "Relocatable schema" does not.

This is the output from both with "default" toggled off, and the value set manually to "false":
![dconfbool2](https://user-images.githubusercontent.com/82701459/117536114-8ea7a100-aff9-11eb-8224-b5837555e174.png)
DConf gets the right value.

I did modify the code in `settings.c` to try and see if I could locate a bug, but I think it's working as it should.

Unless there is a different way to access that setting with GSettings, I don't know what else it could be but a bug in GSettings itself.

**Comment by DarNCelsius** [comment]
How is fastfetch going to get the correct value if the GSettings command line tool can not? The only thing I can think of is the DConf workaround.

**Comment by LinusDierheimer** [comment]
Is it possible that `g_settings_get_value` always returns the same value no matter if the key is set to default or not? Maybe there exists an default "flag" which we need to query for first and if it is set call only `g_settings_get_default_value`.

**Comment by DarNCelsius** [comment]
GSettings always return default for me. I tried multiple variations of 'user' and 'default' calls in `settings.c`, including skipping `g_settings_get_value` entirely. I couldn't get reliable results using GSettings. DConf works for user values, it just doesn't work with defaults. I think the implementation is still being worked on, as it looks a bit unfinished to me.

Either way, it doesn't make sense for the GSettings tool to return the default value if there is a value set by the user.
I don't think I'm using it wrong either:
![gsettingsbug](https://user-images.githubusercontent.com/82701459/117540935-cd495580-b011-11eb-8d6e-3e55cd74d4cd.png)

Fastfetch returns the same values as GSettings with the bool arg. DConf returns NULL for unset values, or true/false when set.

**Comment by LinusDierheimer** [comment]
So we need bool support for dconf? Will work on this as soon as i finished what im currently working on

**Comment by LinusDierheimer** [comment]
Implemented and pushed. Changed the API a bit so you might need to do some minor refactorings.

**Comment by DarNCelsius** [comment]
Now how do I know if DConf returned NULL or the value false?

**Comment by LinusDierheimer** [comment]
You don't. This change was necessary to allow the type cast i need to do to prevent a lot of copies. Maybe treat false like NULL? Still searching for a better way to do this.

**Comment by LinusDierheimer** [comment]
I think i have an idea. Just hang on a bit

**Comment by DarNCelsius** [comment]
The NULL result means the value is in its default state. False is user configured to off - meaning use a custom font, true means user configured to use system font (identical to default).

**Comment by LinusDierheimer** [comment]
you now have a boolValueSet.

**Comment by LinusDierheimer** [comment]
So this can be closed?

**Comment by DarNCelsius** [comment]
Wait a minute. :grin: 

Right now it segfaults. I'll update as soon as I can confirm whether it works or not.

**Comment by DarNCelsius** [comment]
We seem to be in business. :grin: 
All the states are reachable using DConf.
