### ISSUE TITLE
`make install` should respect CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by CarterLi** [LinusDierheimer/fastfetch#272]
https://github.com/LinusDierheimer/fastfetch/blob/master/CMakeLists.txt#L473

**Comment by CarterLi** [comment]
It does exist on macOS

**Comment by LinusDierheimer** [comment]
Then we need to implement it platform specific

**Comment by CarterLi** [comment]
I highly doubt it.

I have Fedora installed in VM. `/usr/local/etc` does exist there ( it's empty though )

<img width="658" alt="image" src="https://user-images.githubusercontent.com/6134068/193321179-c096d191-20e4-4b92-b5a2-47fbca666eff.png">

**Comment by LinusDierheimer** [comment]
Fedora has a thing called "relocatable packages" where (if I understand it correctly) the prefix is decided at install, not packaging time. But this is exclusive to rpm systems
