### ISSUE TITLE
Memory leaks in defaultConfig

### ISSUE THREAD

**Issue by CarterLi** [LinusDierheimer/fastfetch#276]
Every config field ( including module arg ) should be freed / destroyed on program exit

They won't allocate memory by default.  However if users set options ( eg. `--lib-pci "/path/to/library.so"` ) memory will be allocated for storing the option value and will never be freed.

**Comment by ceamac** [comment]
> There is no point in freeing blocks at the end of a program, because all of the program’s space is given back to the system when the process terminates. 

[the glibc manual](https://www.gnu.org/software/libc/manual/html_node/Freeing-after-Malloc.html)

**Comment by CarterLi** [comment]
Yeah. Technically we could never free memories since all modules are executed only once. However we still try hard to free these memories because that is a well coded program should do.

We could have chosen a memory-safe programming language ( even with GC ), but we chose C. It's our duty to do these dirty things.
