### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by kojq** [LinusDierheimer/fastfetch#279]
There is noticeable delay in output upon the first fastfetch from startup or ~10+ seconds after the last fastfetch, while no delay is preferred.

`fastfetch --version`: b0ad129 and ```1.7.2```

**Comment by LinusDierheimer** [comment]
Can you please run `fastfetch --multithreading false` and tell me at what line it hangs?

**Comment by kojq** [comment]
It hangs before any output.

**Comment by kojq** [comment]
The `1.7.5` release is fine, so you can close this issue.

**Comment by LinusDierheimer** [comment]
Interesting, `1.7.5` doesn't contain performance fixes. But i don't complain.
