### ISSUE TITLE
Version commit 89aa4470aa58f3490878d4d5443f7a3a8c9900ad

### ISSUE THREAD

**Issue by schinfo** [LinusDierheimer/fastfetch#28]
![Bildschirmfoto vom 2021-05-05 20-51-35](https://user-images.githubusercontent.com/26834276/117194118-ff757000-ade3-11eb-953b-9a15401ead05.png)

No changes - despite the fixes

**Comment by LinusDierheimer** [comment]
Ensure to build the latest git, then run with --recache

**Comment by schinfo** [comment]
I did that, but it didn't help.
I am always up to date with the current GIT version.

**Comment by schinfo** [comment]
https://gitlab.manjaro.org/packages/community/fastfetch

**Comment by LinusDierheimer** [comment]
`XDG_CURRENT_DESKTOP=X-Cinnamon fastfetch` shows just Cinnamon with the latest commit, so this should work now.
OS code is rewritten, better output now.
I also was too lazy to test the battery code, it should work now.
About the Host, Theme, Icons and GPU see the answer to the email.

Latest version is r220.

**Comment by LinusDierheimer** [comment]
Any updates on this?

**Comment by schinfo** [comment]
![Bildschirmfoto vom 2021-05-08 17-26-30](https://user-images.githubusercontent.com/26834276/117544633-a5162280-b022-11eb-9e7c-53803f32fed7.png)

Version r234 looks good  ;-)

**Comment by LinusDierheimer** [comment]
Great. Closing this.
