### ISSUE TITLE
fatal error while building: CL/cl.h: No such file or directory

### ISSUE THREAD

**Issue by monomycelium** [LinusDierheimer/fastfetch#281]
### resolution

Apparently, `opencl-headers` is needed. Once I installed it with `pacman -S opencl-headers`, it builds successfully. Amazing project, really. I love the speed.

---

### issue

I am running Arch Linux with kernel 5.19.13 from [`linux-surface`](/linux-surface/linux-surface). When I try building from source using the instructions in the readme, I get an error repeatedly and fastfetch does not build at `cmake --build . --target fastfetch --target flashfetch`:

```
/home/ay/fastfetch/src/modules/opencl.c:16:14: fatal error: CL/cl.h: No such file or directory
   16 |     #include <CL/cl.h>
      |              ^~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/libfastfetch.dir/build.make:1126: CMakeFiles/libfastfetch.dir/src/modules/opencl.c.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:87: CMakeFiles/libfastfetch.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:120: CMakeFiles/fastfetch.dir/rule] Error 2
make: *** [Makefile:202: fastfetch] Error 2
```

I have `cmake version 3.24.2`, and `glibc` is installed. Do I need anything else?

**Comment by LinusDierheimer** [comment]
Can you please tell me what the error was? Maybe i can fix it on fastfetch side.
