### ISSUE TITLE
Color blocks are gone

### ISSUE THREAD

**Issue by ceamac** [LinusDierheimer/fastfetch#283]
# General description of bug:
The color blocks on the bottom right are not displayed in the default preset in 1.7.3, they were there in 1.7.2.

![Screenshot from 2022-10-10 07-24-47](https://user-images.githubusercontent.com/50396932/194799225-c30fc7d8-9115-487e-b705-8d0b1b474564.png)

They can be displayed, for example if I run `fastfetch --load-config neofetch` they appear.

Is this intentional?

![Screenshot from 2022-10-10 07-39-54](https://user-images.githubusercontent.com/50396932/194800170-251f0d8e-0c69-4a2f-b3aa-fb62598d7655.png)

**Comment by LinusDierheimer** [comment]
Fixed.
