### ISSUE TITLE
Suggestion: Remove GPU number with single GPU

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#30]
I think it would look better on systems with only one GPU installed to simply have 'GPU' displayed without the following number.

**Comment by LinusDierheimer** [comment]
Is it possible that this bug only occurs  when recaching the data? Because in the gpu code this expected behavior while in the caching code it should't print a number. Sadly i can't just take a gpu out of my laptop to test this.

**Comment by DarNCelsius** [comment]
The result is the same with no args, --nocache and --recache.
![gpubug](https://user-images.githubusercontent.com/82701459/117540398-85c1ca00-b00f-11eb-8db9-017622734c5d.png)

**Comment by LinusDierheimer** [comment]
Offtopic but for another issue i'm working on, could you show me the content of your /etc/os-release?

**Comment by LinusDierheimer** [comment]
Also off topic, but why doesn't it remove ` Processor` from your CPU output? It should: https://github.com/LinusDierheimer/fastfetch/blob/bd316496a2ed5ad2192a481b376c2487adbe8c04/src/modules/cpu.c#L103

**Comment by DarNCelsius** [comment]
model name:
`AMD Ryzen 7 3800X 8-Core Processor`

/etc/os-release:
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
I'll look into `gpu.c`

**Comment by LinusDierheimer** [comment]
Then take a look at https://github.com/LinusDierheimer/fastfetch/blob/bd316496a2ed5ad2192a481b376c2487adbe8c04/src/common/io.c#L247
Does it pass this check or not?

**Comment by DarNCelsius** [comment]
It jumps to `instance->config.recache = true;`
![gpubug3](https://user-images.githubusercontent.com/82701459/117542267-37fd8f80-b018-11eb-9831-331645fd6c5d.png)
String buffer content looks to be corrupt?

**Comment by LinusDierheimer** [comment]
What is the content of the strbuf?

**Comment by DarNCelsius** [comment]
Look top left - "chars"

**Comment by DarNCelsius** [comment]
No

**Comment by LinusDierheimer** [comment]
Expected but i hoped so

**Comment by DarNCelsius** [comment]
![gpubug4](https://user-images.githubusercontent.com/82701459/117542926-e99dc000-b01a-11eb-84e8-92a2114af06e.png)

**Comment by DarNCelsius** [comment]
`r210.bd2e1da%`

**Comment by LinusDierheimer** [comment]
right string, but outdated version. Very weird. Does a manual removal of ~/.cache/fastfetch/ help?

**Comment by DarNCelsius** [comment]
No. Should the folder be recreated with --recache, btw? It is not.

**Comment by LinusDierheimer** [comment]
Yes it should. And it "works on my machine". So after a manual removal of your cache folder and a run of fastfetch the folder doesn't exist?

**Comment by DarNCelsius** [comment]
Correct. Neither the system version (210) or the dev version (230) creates the folder.

**Comment by DarNCelsius** [comment]
```
╰─ echo $XDG_CACHE_HOME
/home/darn/.cache
```

**Comment by LinusDierheimer** [comment]
Does a ~/cachefastfetch folder exist? Think i found a bug

**Comment by LinusDierheimer** [comment]
Pull latest commit.

**Comment by DarNCelsius** [comment]
That did it:
![gpubug5](https://user-images.githubusercontent.com/82701459/117543912-2d92c400-b01f-11eb-9ce2-5f91bf8671ec.png)
Initial run and subsequent run.

**Comment by LinusDierheimer** [comment]
Great. Then i look into making the initial run working too.

**Comment by DarNCelsius** [comment]
Folder is back too. :+1:

**Comment by LinusDierheimer** [comment]
Should now also work when not recaching
