### ISSUE TITLE
Promote FS type to disk format string

### ISSUE THREAD

**Issue by LinusDierheimer** [LinusDierheimer/fastfetch#300]
### Discussed in https://github.com/LinusDierheimer/fastfetch/discussions/299

<div type='discussions-op-text'>

<sup>Originally posted by **Richard-Rogalski** October 15, 2022</sup>
Fastfetch has a lovely ability to display thing like: `Disk (/): 47.32 GiB / 721 GiB (6%)`, which is great :D.  

I think it would be pretty darn nifty if it could append the filesystem: for example, `[zfs]`, `[ext4]`, `[ntfs]`, and so on.

Thanks for this incredible project, and for taking the time to read this :)</div>

**Comment by LinusDierheimer** [comment]
You can now (dev branch) use the following format string to print the file system on all platforms:
```
fastfetch --disk-format "{1} / {2} ({3}%) [{9}] {?7}[Removable]{?}"
```
Put it `{XDG_CONFIG_HOME:~/.config}/fastfetch/config.conf` to make it permanent.

To learn more about the disk format string, use `fastfetch --help disk-format`.

**Comment by CarterLi** [comment]
Do we still support --disk-folder on Windows?

Note windows mountpoint (drive / volume) `C:\` contains `:`
