### ISSUE TITLE
X11 Behavior

### ISSUE THREAD

**Issue by kojq** [LinusDierheimer/fastfetch#304]
# General description of bug:

Regarding #279, it seems that this issue of noticeable delay in output (upon the first fastfetch from startup or ~10+ seconds after the last fastfetch) occurs on X11, whereas it is fine on Wayland.

**Comment by CarterLi** [comment]
Please check if this issue remains. `fastfetch --stat` may help

**Comment by kojq** [comment]
The issue remains and was currently tested using new install of Arch Linux with GNOME (on Console) and KDE (on Konsole).

**Comment by CarterLi** [comment]
I personally can't reproduce this issue. If it remains, please open a new issue and attach the output of `fastfetch --stat`

Closing as stale
