### ISSUE TITLE
Cargo packages

### ISSUE THREAD

**Issue by Samisafool** [LinusDierheimer/fastfetch#318]
# Current state:
Does not count cargo packages

# Wanted state:
Counts cargo packages

# Why the change is sensible:
More package managers

[this](https://stackoverflow.com/questions/60857222/how-do-i-list-all-of-the-packages-ive-installed-globally-with-cargo-install) might be helpful for quickly finding how many are installed

**Comment by LinusDierheimer** [comment]
I agree that a non system package manager shouldn't be printed by default. But it might make Sense to expose it to the format string. @CarterLi What do you think about that?

**Comment by CarterLi** [comment]
What about a user defined module, to execute a small batch script?

**Comment by LinusDierheimer** [comment]
That is something i absolutely want, but this is so general purpose, the user should be able to use it multiple times, and i am not sure how to implement that using the current config system.
