### ISSUE TITLE
Packaging for scoop (Windows), Chocolatey (Windows), pkg (FreeBSD)

### ISSUE THREAD

**Issue by CarterLi** [LinusDierheimer/fastfetch#320]
Also don't package flashfetch, as it's meant to be built from source. Including two binaries may confuse users

**Comment by LinusDierheimer** [comment]
I thought the same and disabled it in the past, but then i was explicitly asked to package it again, see https://aur.archlinux.org/packages/fastfetch-git?O=10#comment-859498

**Comment by CarterLi** [comment]
Ok.

Will we have 1.8.0 soon?

**Comment by LinusDierheimer** [comment]
There are things i wanted to push before, but they can wait for 1.9 too. What do you think about now? I have time today.

**Comment by CarterLi** [comment]
Lets wait for your pushing

**Comment by vvirtues** [comment]
would be very useful for scoop users like me

**Comment by he3als** [comment]
Windows builds aren't currently in GitHub releases, how would that work for Scoop?

**Comment by sitiom** [comment]
PR for Scoop in Main bucket: https://github.com/ScoopInstaller/Main/pull/4334

**Comment by sitiom** [comment]
@CarterLi Winget 1.4 has been released, supporting zip file installation (https://github.com/microsoft/winget-cli/releases/tag/v1.4.10173).

Please consider packaging for Winget as well. I have already created an initial PR to add fastfetch to winget-pkgs: https://github.com/microsoft/winget-pkgs/pull/94697. [Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser) would have to be set up in this repo to push out automatic updates to the manifest.

Ping @vedantmgoyal2009, Is Winget Releaser ready for the 1.4 manifests?

**Comment by vedantmgoyal2009** [comment]
Thanks for reminding me. I'll do it by end of this month.

**Comment by CarterLi** [comment]
Scoop has been supported. Request for chocolatey [has been opened for several months](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1395) but seems no one cares ( I personally don't use choco ).

And I can't even find where to submit package request for FreeBSD...

Closing as stale. @sitiom if you need my help in the future, feel free to open new issues.
