### ISSUE TITLE
Improve line wrap handling

### ISSUE THREAD

**Issue by CarterLi** [LinusDierheimer/fastfetch#321]
# Current state:

With `--disable-linewrap` enabled, fastfetch hardly truncates text exceed one line, which is not very friendly

<img width="889" alt="image" src="https://user-images.githubusercontent.com/6134068/198255539-5a4eb42f-d064-4998-b8b2-82043a6bc5b9.png">

# Wanted state:

Don't print less important information when text may exceeding

For example, don't print artist in the case above. If the text still may exceeding without artist, don't print playing status too.

**Comment by CarterLi** [comment]
Closing as not planned

**Comment by luni3359** [comment]
You used the wrong close type
