### ISSUE TITLE
`Segmentation fault (core dumped)` when using {0} on a format

### ISSUE THREAD

**Issue by jumps-are-op** [LinusDierheimer/fastfetch#326]
# General description of bug:
when using `{0}` on a format fastfetch will fail with segmentation fault

# Often helpful questions:
* Does the issue occur across multiple shells? Yes

Output of `fastfetch --version`:
```
fastfetch 1.7.5
```

Output of `fastfetch --load-config devinfo`:
![fastfetch_bug_report](https://user-images.githubusercontent.com/91761043/199073257-8282ed35-32fe-41cb-87ec-fd465aa07cbd.png)

Output of `fastfetch --list-features`:
```
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
```

**Comment by LinusDierheimer** [comment]
Fixed. Thanks for reporting.
