### ISSUE TITLE
Add simpler build instructions for Windows

### ISSUE THREAD

**Issue by vvirtues** [LinusDierheimer/fastfetch#336]
# Current state: Too complex for users to understand how to build

# Wanted state: Simple build instructions

# Why the change is sensible: Make it easer for everyone to build instead of trusting someone else's sketchy files
I hope this is easy to understand

**Comment by CarterLi** [comment]
I'm the maintainer of the fastfetch windows version.

As currently Visual Studio (MSVC) is not supported, you have to setup a MinGW environment, alongside with cmake, pkg-config, gnu-make / ninja, etc.

The easiest way to go is to use [MSYS2](https://www.msys2.org/) as said in [README](https://github.com/LinusDierheimer/fastfetch#building-on-windows). To setup a MSYS2 environment, please follow the instructions on the [MSYS2 official website](https://www.msys2.org/).

If you think it is complex, download the prebuilt binaries provided [here](https://github.com/LinusDierheimer/fastfetch/actions). It's build by machine (not **someone**) and you can find all build steps [here](https://github.com/LinusDierheimer/fastfetch/blob/dev/.github/workflows/push.yml#L126). If you don't trust the code, don't use this project.
