### ISSUE TITLE
DE/WM detection broken

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#34]
Fastfetch fails to recognize LXDE/Openbox
![lxdeobBug](https://user-images.githubusercontent.com/82701459/117562924-b0a92e00-b0a2-11eb-9a57-98c7b27f17b4.png)
DE should be LXDE, WM should be Openbox

edit: LXQT/regular Openbox is working as intended

**Comment by LinusDierheimer** [comment]
Is it possible that in a LXDE session, the process name of Openbox doesn't match "openbox"?

**Comment by DarNCelsius** [comment]
![lxdeobBug2](https://user-images.githubusercontent.com/82701459/117568863-13122680-b0c3-11eb-8e16-9295a7dd6472.png)

**Comment by LinusDierheimer** [comment]
What is the output of `fastfetch --wm-format "{}; {}; {}; {};"`?

**Comment by DarNCelsius** [comment]
`WM: LXDE; LXDE; LXDE; X11;`

**Comment by DarNCelsius** [comment]
Seems to confuse DE with WM?

**Comment by LinusDierheimer** [comment]
This means it doesn't find a process name which matches a known WM process name, so it sets `$XDG_SESSION_DESKTOP` (output 1) as `result.processName` (output 2) and `result.prettyName` (output 3). This is especially weird as we have openbox implemented:
```c
else if(ffStrbufIgnCaseCompS(processName, "openbox") == 0)
{
    ffStrbufSetS(&result->wmPrettyName, "Openbox");
    *protocolHint = FF_PROTOCOL_HINT_X11;
}
```
and this works for LXQT. Can you dig deeper into this?

**Comment by LinusDierheimer** [comment]
I think i found the bug. Try with latest commit.

**Comment by DarNCelsius** [comment]
Ok. Putting this in here before that:
![lxdeobBug3](https://user-images.githubusercontent.com/82701459/117569460-122ec400-b0c6-11eb-8984-4ecbf19acbb6.png)
The command line differs. LXQT uses no args.

**Comment by LinusDierheimer** [comment]
Yes i think the problem was arguments containing the / char.

**Comment by DarNCelsius** [comment]
Case closed :+1: 
![lxdeobBug4](https://user-images.githubusercontent.com/82701459/117569591-b0bb2500-b0c6-11eb-9e4a-e406d12a5139.png)
