### ISSUE TITLE
suggest update README.md

### ISSUE THREAD

**Issue by kojq** [LinusDierheimer/fastfetch#343]
In the [README.md](https://github.com/LinusDierheimer/fastfetch#readme):

> At the moment the performance difference is measurable, but too small to be human recognizable. But the leap will get bigger with more and more options coming, and on slow machines this might actually make a difference.

I would consider any difference to be statistically negligible, unless you could demonstrate otherwise (for instance, by referencing a file of output times for given configurations).

Also, consider fewer images in the README and potentially a screenshot of an OS other than Linux using fastfetch.

**Comment by CarterLi** [comment]
> potentially a screenshot of an OS other than Linux using fastfetch.

Did it here: https://github.com/dylanaraps/neofetch/issues/2257

**Comment by kojq** [comment]
Will you choose to commit any change to the README regarding the screenshots?

**Comment by CarterLi** [comment]
See https://github.com/LinusDierheimer/fastfetch/wiki
