### ISSUE TITLE
Add option to work with Cowsay

### ISSUE THREAD

**Issue by sbstn87** [LinusDierheimer/fastfetch#345]
Hi,

will it be possible to use fastfetch together with Cowsay, just like neofetch can be used?

It is described in point 7 in this guide for neofetch:
https://itsfoss.com/using-neofetch/

**Comment by LinusDierheimer** [comment]
`fastfetch --data-raw "$(fortune | cowsay -W 30)" | lolcat` does work now and will be included in the next release. Use the git version until then.
