### ISSUE TITLE
After dipping my CPU, the old one is still displayed.

### ISSUE THREAD

**Issue by FrankBG67** [LinusDierheimer/fastfetch#346]
![Screenshot_20221210_193212](https://user-images.githubusercontent.com/63481435/206870177-8a94c70f-0a40-4354-ba5f-e4ad892ddf3a.png)
# General description of bug:
After dipping my CPU, the old one is still displayed.

# Often helpful questions:
* Does the issue occur across multiple terminal emulators? [Y]
* Does the issue occur across multiple shells? (bash, zsh) [Y]

Output of `fastfetch --version`: 
fastfetch 1.7.5
```

Output of `fastfetch --load-config devinfo`:
```
 ||||||||| ||||    ┌──────────────────────────────────────────┐
 ||||||||| ||||    fbg@FBG
 ||||      ||||          1 day, 1 hour, 8 mins
 |||| |||| ||||    └──────────────────────────────────────────┘
 |||| |||| ||||    ┌────────── Hardware Information ──────────┐
 |||| |||| ||||          neither product_family nor product_name is set by O.E.M.
 |||| |||| ||||          AMD Ryzen 7 5800X (16) @ 4.850195 GHz
                     ﬙    AMD Radeon RX 6600 XT
                         1920x1200 @ 60Hz
                         1920x1200 @ 60Hz
                     﫭    196 GiB / 219 GiB (89%)
                   ├────────── Software Information ──────────┤
                         Manjaro Linux x86_64
                         6.0.11-1-MANJARO
                         KDE Plasma 5.26.4
                         KWin (X11)
                         zsh 5.9
                         konsole
                         Source Code Pro (12pt, Light)
                         2026 (pacman)[stable], 14 (flatpak)
                   └──────────────────────────────────────────┘

```

Output of `fastfetch --load-config devinfo-verbose`:
<!--
Note that this output will contain you public IP. If it is not relevant for the issue, feel free to remove it before uploading.
-->
```
(base) [fbg@FBG ~]$ fastfetch --load-config devinfo-verbose
 ||||||||| ||||    fbg@FBG
 ||||||||| ||||    -------
 ||||      ||||          System: Linux; Name: Manjaro Linux; Pretty name: Manjaro Linux; ID: manjaro; ID like: arch; Variant: ; Variant ID: ; Version: ; Version ID: ; Version codename: ; Build ID: rolling; Architecture: x86_64
 |||| |||| ||||          neither product_family nor product_name is set by O.E.M.
 |||| |||| ||||          Sysname: Linux; Release: 6.0.11-1-MANJARO; Version: #1 SMP PREEMPT_DYNAMIC Fri Dec 2 21:23:52 UTC 2022
 |||| |||| ||||          Days: 1; Hours: 1; Minutes: 9; Seconds: 35
                   Processes    Count: 1217
                         All: 2040; pacman: 2026; pacman branch: stable; dpkg: 0; rpm: 0; emerge: 0; xbps: 0; apk: 0; flatpak: 0; snap: 0; brew: 0
                         Process name: zsh; Process path: /bin/zsh; Process exe: zsh; Process version: 5.9; User path: /bin/zsh; User exe: zsh; User version: 5.9
                         Width: 1920; Height: 1200; Refresh rate: 60
                         Width: 1920; Height: 1200; Refresh rate: 60
                         Process name: plasmashell; Pretty name: KDE Plasma; Version: 5.26.4
                         Process name: /usr/bin/openbox; Pretty name: KWin; Protocol: X11
                   WM Theme    Name: Manjaro-Cyan-Aurorae
                   Theme    Plasma: Breeze; Plasma colors: ManjaroCyanDarkColor; Plasma colors pretty: ManjaroCyanDarkColor; GTK2: Materia-Manjaro-Dark-gtk; GTK3: Materia-Manjaro-Dark-gtk; GTK4: Materia-Manjaro-Dark-gtk; GTK: Materia-Manjaro-Dark-gtk [GTK2/3/4]
                   Icons    Plasma: Cyan-Breeze-Dark-Icons; GTK2: Cyan-Breeze-Dark-Icons; GTK3: Cyan-Breeze-Dark-Icons; GTK4: Cyan-Breeze-Dark-Icons; GTK: Cyan-Breeze-Dark-Icons [GTK2/3/4]
                   Font    Font1: Noto Sans (11pt); Font2: Noto Sans (11pt); Font3: Noto Sans (11pt); Font4: Noto Sans (11pt)
                   Cursor    Theme: breeze; Size: 24
                         Process: konsole; Path: /usr/bin/konsole; Exe: konsole
                         Pretty: Source Code Pro (12pt, Light); Name: Source Code Pro; Size: 12; Styles: Light
                         Name: AMD Ryzen 7 5800X, Vendor: AuthenticAMD, CoresPhysical: 8, CoresLogical: 32, CoresOnline: 16, FrequencyMin: 2.2, FrequencyMax: 4.85019, Temperature: -nan
                     ﬙    Vendor: AMD; Name: Radeon RX 6600 XT; Driver: amdgpu; Temperature: -nan; CoreCount: -1
                   Memory    Used: 3.85 GiB; Total: 31.26 GiB; Percentage: 12
                   Swap    Disabled
                     﫭    Used: 196 GiB; Total: 219 GiB; Files: 89; Percentage: 1548811
                   Battery    batteryDir doesn't contain any battery folder
                   Power Adapter    Unimplemented
                   Media Player    No media found
                   Media    No media found
                   Local IP (enp5s0)    192.168.98.16
                   Date & Time    year: 2022; yearShort: 22; month: 12; monthPretty: 12; monthName: December; monthNameShort: Dec; weekNumber: 50; weekday: Saturday; weekdayShort: Sat; dayInYear: 88; dayInMonth: 10; dayInWeek: 6; hour: 19; hourPretty: 19; hour12: 7; hour12Pretty: 07; minute: 37; minutePretty: 37; second: 15; secondPretty: 15
                   Locale    de_DE.UTF-8
                   Vulkan    driver: radv [Mesa 22.2.4]; Api Version: 1.3.224; Conformance Version: 1.3
                   OpenGL    version: 4.6 (Compatibility Profile) Mesa 22.2.4; renderer: AMD Radeon RX 6600 XT (navi23, LLVM 14.0.6, DRM 3.48, 6.0.11-1-MANJARO); vendor: AMD
                   OpenCL    clGetPlatformIDs returned 0 platforms
                   Users    fbg
                   Weather    -5°C - Clear (Lebach, Germany)

```

Output of `fastfetch --list-features`:
```
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl

```

<!--
If you get the following error: `Error: couldn't find config: [...]`, copy the files in [presets](../../presets/) to `/usr/share/fastfetch/presets/` or `~/.local/share/fastfetch/presets/`.
If this isn't possible (or too much work) for you, post the output of `fastfetch --show-errors --recache --multithreading false --disable-linewrap false`. 
-->

**Comment by LinusDierheimer** [comment]
Try running with `--recache` once

**Comment by FrankBG67** [comment]
Perfect, It all works now.
