### ISSUE TITLE
Build Fail On MSYS2

### ISSUE THREAD

**Issue by Danik2343** [LinusDierheimer/fastfetch#351]
![mintty_C9xPP0io49](https://user-images.githubusercontent.com/38865696/208192968-9fe94a27-b17b-4a59-ae7f-6e93bba12ae4.png)

**Comment by CarterLi** [comment]
You need [environment](https://www.msys2.org/docs/environments/) other than MSYS. [CLANG64 and UCRT64 are more actively tested and recommended](https://github.com/LinusDierheimer/fastfetch#building-on-windows).
