### ISSUE TITLE
Solus is missing

### ISSUE THREAD

**Issue by theunclemez** [LinusDierheimer/fastfetch#360]
Hello Team

I'm a Solus user who just discovered this amazing app today, well i managed to make it work on Solus but few stuffs are lacking such as the proper distro logo + package manager
Possible to have Solus added  into the list so i can submit request for fastfetch to be added to Solus repos?
[](url)
![Screenshot from 2022-12-26 12-24-18](https://user-images.githubusercontent.com/50036470/209545652-800784b1-a56e-41e8-8e9e-3c701ca0a5dd.png)

**Comment by CarterLi** [comment]
I have added package manager support for Solus based [the implementation of neofetch (eopkg I suppose)](https://github.com/hykilpikonna/hyfetch/blob/master/neofetch#L1857). Please test it

**Comment by CarterLi** [comment]
Closing as stale. Please open a new issue if something goes wrong.
