### ISSUE TITLE
Rookie mistake!

### ISSUE THREAD

**Issue by keybreak** [LinusDierheimer/fastfetch#364]
New version of `fastfetch` started to enumerate individual disks, but someone forgot to wrap paths in quotes...some people use spaces, you know :smile: 

For example:
~~~
/run/media/x133/STORAGE 1
~~~

of course gives a:

~~~bash
Disk (/run/media/x133/STORAGE\0401): Unknown [Removable]
~~~

P.S. btw, i use Arch! :rofl:

**Comment by CarterLi** [comment]
I don't think it has something to do with quotes. Paths need quotes when used in shell commands, but it's not the case for fastfetch.

Maybe this line? https://github.com/LinusDierheimer/fastfetch/blob/dev/src/detection/disk/disk_linux.c#L44

**Comment by LinusDierheimer** [comment]
This was a bit more complicated than just adding quotes, because the kernel encodes special characters in `/proc/mounts` a way i have never seen before... However i now decode those before further processing, so it should be working now. Thanks for reporting.

**Comment by keybreak** [comment]
Yeah i know, quotes was a bit tongue-in-cheek  for a definition of a classical problem :laughing: 
Thx for fixing and making a best fetch out there! :partying_face:

**Comment by LinusDierheimer** [comment]
No problem, as soon as i find a solution for #366 i will release 1.8.1 containing the fix.
