### ISSUE TITLE
ffPrintError output

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#37]
regex causes newline output from `printTerminalFontFromConfigFile`:
![regexBug](https://user-images.githubusercontent.com/82701459/117571410-b583d700-b0ce-11eb-8f33-b5947f5cb7c0.png)

**Comment by LinusDierheimer** [comment]
Resolving this as soon we merged your XFCE Terminal Font code, to prevent unneeded merge conflicts.

**Comment by LinusDierheimer** [comment]
Fixed with latest commit.
