### ISSUE TITLE
Device selection

### ISSUE THREAD

**Issue by bekaertruben** [LinusDierheimer/fastfetch#379]
# Current state:
When showing devices such as disks or gpu, multiple can be shown.

For example, a dedicated and integrated gpu:
![2023-01-07_12-30](https://user-images.githubusercontent.com/43539018/211148654-f1c14107-696d-447e-a18c-97f3490a0542.png)

And multiple partitions:
![2023-01-07_12-34](https://user-images.githubusercontent.com/43539018/211148667-c87a6175-8ad9-499c-9a59-25fd2a30fe36.png)

# Wanted state:
In this example, I would like to be able to only show the dedicated nvidia gpu (neofetch has this feature with gpu_type="dedicated", but it doesn't appear work for my hardware).  

As for the disks, 4 of these are actually the same partition (hence they have the same capacity and free space), but with btrfs subvolumes, and the other two are seconday storage.  

There should ideally be filters to select:
- only dedicated or integrated gpu
- only (un)"removable" disks
- manually blacklist some devices  
The latter is probably the easiest to implement.

# Why the change is sensible:
This change would allow the user to show only info that they care about.  
This is a not a high priority issue, but seems like an important customizability feature to me.

**Comment by CarterLi** [comment]
> only (un)"removable" disks

There is an option called [`--disk-show-removable`](https://github.com/LinusDierheimer/fastfetch/blob/dev/src/data/help.txt#L107). You may set it to false to hide removable disks.

> manually blacklist some devices

There is an option called [`--disk-folders`](https://github.com/LinusDierheimer/fastfetch/blob/dev/src/data/help.txt#L106). You may set it to what disks you care about.

> only dedicated or integrated gpu

Probably no before I have a dedicated gpu

**Comment by bekaertruben** [comment]
Oh you just added them, even better. Thanks for adding it ;)

**Comment by LinusDierheimer** [comment]
I am working on the GPU thing right now, but its harder than it seems. There is no obvious way from a pci pov to differentiate them.
Neofetchs implementation is to show intel only if the type is integrated, nvidia only if the type is dedicated, and AMD always. With intel now producing dedicated GPUs as well that is not a solution i want to use.

For example, this is my integrated vs dedicated GPU:
```
03:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] (rev c2)
        Subsystem: Dell Device 09f5
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR+ FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0, Cache Line Size: 64 bytes
        Interrupt: pin A routed to IRQ 81
        IOMMU group: 11
        Region 0: Memory at 600000000 (64-bit, prefetchable) [size=8G]
        Region 2: Memory at 500000000 (64-bit, prefetchable) [size=2M]
        Region 5: Memory at d0700000 (32-bit, non-prefetchable) [size=512K]
        Expansion ROM at d07a0000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu

07:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev c6) (prog-if 00 [VGA controller])
        Subsystem: Dell Device 09f5
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort+ <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0, Cache Line Size: 64 bytes
        Interrupt: pin A routed to IRQ 56
        IOMMU group: 6
        Region 0: Memory at fc80000000 (64-bit, prefetchable) [size=256M]
        Region 2: Memory at fc90000000 (64-bit, prefetchable) [size=2M]
        Region 4: I/O ports at 1000 [size=256]
        Region 5: Memory at d0300000 (32-bit, non-prefetchable) [size=512K]
        Capabilities: <access denied>
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu
```

Maybe we can use the device class? More data from more GPUs would be helpfull.

**Comment by bekaertruben** [comment]
If that is so, then we would only need to find a difference between intel integrated and discrete

**Comment by LinusDierheimer** [comment]
Not going to work: https://www.reddit.com/r/VFIO/comments/kvvrwl/intel_igpu_shows_as_display_controller_instead_of/

**Comment by bekaertruben** [comment]
I know a better solution. It's still a bit of a hack, but it should be a decent discriminator.
All of the iGPUs have use RAM as memory and thus have only very little memory integrated. The discrete cards always have memories in the gigabytes
```
your card:
        Region 0: Memory at 600000000 (64-bit, prefetchable) [size=8G]
mine:
	Memory at fb00000000 (64-bit, prefetchable) [size=4G]
```
You could just choose that all cards with more than some arbitrary limit in VRAM like 1GB must be dedicated (very old cards may fail, like the gt210 which has only 512 MB, but this should work for anything remotely modern).

**Comment by LinusDierheimer** [comment]
I have added two options:
* `--gpu-hide-integrated`
* `--gpu-hide-discrete`

Can you please test them?

**Comment by LinusDierheimer** [comment]
Please try again.

**Comment by bekaertruben** [comment]
It now appears to be working as expected.
Thanks a lot for adding this!
