### ISSUE TITLE
WM Confusion

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#38]
WM Theme detection on LXQT/XFWM seems broken:
![lxqtxfwm](https://user-images.githubusercontent.com/82701459/118010318-351fd900-b34f-11eb-9d04-722ca3659f82.png)

**Comment by LinusDierheimer** [comment]
This seems to doesn't work at all because XFWM should be shown Xfwm4. What is the process name of XFWM?

**Comment by DarNCelsius** [comment]
1286975 tty7     Sl+    0:00 /usr/bin/xfwm4

**Comment by DarNCelsius** [comment]
My bad - this was with r242. 264 work fine.
