### ISSUE TITLE
Icon, cursor and GTK theme are not reported correctly

### ISSUE THREAD

**Issue by algent-al** [LinusDierheimer/fastfetch#382]
# General description of bug:

I am comparing `fastfetch` with `neofetch`. As you can notice `fastfetch` is reporting wrong Icons, cursor and GTK theme. They are as reported with `neofetch`.

![figurë](https://user-images.githubusercontent.com/46356616/211211929-17adbc4f-42a0-42aa-80a3-b61fe31dca50.png)

# Often helpful questions:
* Does the issue occur across multiple terminal emulators? [Y]
  - `tilix`
  - `gnome-terminal`
  - `terminator`
* Does the issue occur across multiple shells? (bash, zsh, fish, etc) [Y/N]

Output of `fastfetch --version`:
```
fastfetch 1.8.2
```

Output of `fastfetch --load-config devinfo`:
![figurë](https://user-images.githubusercontent.com/46356616/211212065-d5f44461-a43c-4159-9d01-4a4e83546cea.png)

Output of `fastfetch --list-features`:
```
gio
dbus
zlib
```

**Comment by algent-al** [comment]
Added more features but still the issue is not resolved.
![figurë](https://user-images.githubusercontent.com/46356616/211215327-22d4d11f-22d0-413b-b1b0-c1dfed0eea1a.png)

**Comment by LinusDierheimer** [comment]
Should work now.

**Comment by algent-al** [comment]
Partly fixed.

Icon theme and gtk theme are detected fine.

![fastfetch](https://user-images.githubusercontent.com/46356616/212743177-f6195d77-cd8b-4a58-a1f3-6326c5c0b2bf.png)

Cursor should be "Vimix" in this case.

**Comment by LinusDierheimer** [comment]
Do you know the dconf path where it is stored?

**Comment by algent-al** [comment]
This is the dconf path. 
![figurë](https://user-images.githubusercontent.com/46356616/212747688-5ef73f4d-8431-4981-a607-9f82655f5987.png)

`fastfetch` reads the default value I guess.

**Comment by algent-al** [comment]
And this command working fine in terminal:
`gsettings set org.gnome.desktop.interface cursor-theme "Bibata-Original-Ice"`

**Comment by algent-al** [comment]
Probably unrelated but there is a missing letter `f`.
![figurë](https://user-images.githubusercontent.com/46356616/212772943-b8c494c3-4681-49eb-b1f2-ebde9a8bf4ba.png)

**Comment by LinusDierheimer** [comment]
> Probably unrelated but there is a missing letter `f`.

https://github.com/LinusDierheimer/fastfetch/commit/8a054706b5efd6d50db4cf92388d62a94d50f4ca

**Comment by LinusDierheimer** [comment]
Should also be working now.

**Comment by algent-al** [comment]
> Should also be working now.

Yes. It is fixed. Thanks!
