### ISSUE TITLE
fastfetch not working in chroot with busybox 

### ISSUE THREAD

**Issue by aidgamesa** [LinusDierheimer/fastfetch#385]
# General description of bug:
fastfetch not working in chroot with busybox 

Output of `fastfetch --version`:
```
fastfetch 1.8.2-72
```

Output of `fastfetch --load-config devinfo`:
```
Error: couldn't find config: devinfo
```

Output of `fastfetch --load-config devinfo-verbose`:
```
Error: couldn't find config: devinfo-verbose
```

Output of `fastfetch --list-features`:
```
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
zlib
sqlite3
egl
glx
osmesa
```

/ # /fastfetch --show-errors --multithreading false --disable-linewrap false
Segmentation fault (core dumped)
/ # mount 
proc on /proc type proc (rw,relatime)
devtmpfs on /dev type devtmpfs (rw,relatime,size=1953080k,nr_inodes=488270,mode=755,inode64)
sysfs on /sys type sysfs (rw,relatime)

**Comment by LinusDierheimer** [comment]
Can you please provide the output of `strace fastfetch --multithreading false --show-errors true`?

**Comment by aidgamesa** [comment]
sorry, i can't because i have only busybox in chroot

**Comment by aidgamesa** [comment]
`execve("/fastfetch", ["/fastfetch", "--multithreading", "false", "--show-errors", "true"], 0x7fffb5ce5460 /* 18 vars */) = 0
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffe6ed81b30) = -1 EINVAL (Invalid argument)
brk(NULL)                               = 0x7ca000
brk(0x7cad40)                           = 0x7cad40
arch_prctl(ARCH_SET_FS, 0x7ca3c0)       = 0
set_tid_address(0x7ca690)               = 467457
set_robust_list(0x7ca6a0, 24)           = 0
rseq(0x7cace0, 0x20, 0, 0x53053053)     = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
readlink("/proc/self/exe", "/fastfetch", 4096) = 10
getrandom("\x68\x32\x89\xcf\x65\xaa\xc9\xeb", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x7cad40
brk(0x7ebd40)                           = 0x7ebd40
brk(0x7ec000)                           = 0x7ec000
mprotect(0x549000, 16384, PROT_READ)    = 0
getuid()                                = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(3)                                = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(3)                                = 0
newfstatat(AT_FDCWD, "/etc/nsswitch.conf", 0x7ffe6ed80650, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/passwd", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
uname({sysname="Linux", nodename="archlinux", ...}) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x20} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)`

**Comment by aidgamesa** [comment]
oh, it's problem because i don't have /etc/passwd
i just copy from my host os to etc/passwd and it works!
```[user@archlinux build]$ sudo chroot . /bin/sh
/ # /fastfetch
        #####            root@archlinux
       #######           --------------
       ##O#O##           OS: Linux x86_64
       #######           Host: Profice VL500 (012010)
     ###########         Kernel: 6.1.1-arch1-1
    #############        Uptime: 6 hours, 39 mins
   ###############       Resolution: 1280x1024
   ################      WM: i3 (X11)
  #################      Terminal: kitty
#####################    CPU: Intel(R) Core(TM)2 Duo     E8400 (2) @ 2.997 GHz
#####################    Memory: 1.86 GiB / 3.76 GiB (49%)
  #################      Locale: ru_RU.UTF-8```

**Comment by LinusDierheimer** [comment]
I am glad to hear you fixed it! However i still will look into better error handling when `uname` fails.

**Comment by aidgamesa** [comment]
good luck!
