### ISSUE TITLE
Icons and custom text

### ISSUE THREAD

**Issue by se7en-x230** [LinusDierheimer/fastfetch#386]
# Current state:

# Wanted state:
![image](https://user-images.githubusercontent.com/69777713/211811389-eeb6cd3f-3262-4ccc-90e2-7b54553e00a1.png)

# Why the change is sensible:

**Comment by se7en-x230** [comment]
Found it sorry.

**Comment by se7en-x230** [comment]
![shop-2023-01-12-13-52](https://user-images.githubusercontent.com/69777713/211997873-d22655ab-3247-4443-9d46-b10328be6195.png)


Nice and so much faster.

Thanks

**Comment by Dan1jel** [comment]
> Found it sorry.

Might share where you found it? Would be nice for future like me :)
