### ISSUE TITLE
--precent-type

### ISSUE THREAD

**Issue by se7en-x230** [LinusDierheimer/fastfetch#387]
# Current state:
![x230-12-01-2023_20-42](https://user-images.githubusercontent.com/69777713/212082160-b1a68422-d70a-4adf-87a6-e28743240274.png)

# Wanted state:
--percent-type with a setting to have the bar {2} and ONLY the % OR use a less space consuming format 100/120 GB

# Why the change is sensible:
Less space

**Comment by CarterLi** [comment]
Please try `--percent-type 6` with `GIT HEAD`

**Comment by se7en-x230** [comment]
fastfetch/src/modules/opencl.c:16:14: fatal error: CL/cl.h: No such file or directory

  16 |     #include <CL/cl.h>
      |              ^~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/libfastfetch.dir/build.make:832: CMakeFiles/libfastfetch.dir/src/modules/opencl.c.o] Error 1

sorry can't find out why it's not building

**Comment by se7en-x230** [comment]
Thanks for the fast response
Works perfectly.

An option bar + percentage would be in my setup optical the nicest and then all combinations would be possible.

**Comment by CarterLi** [comment]
Would you mind share your configuration?

**Comment by se7en-x230** [comment]
> Would you mind share your configuration?

sure https://0x0.st/o7tJ.conf
