### ISSUE TITLE
Tilix terminal font detection fails

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#39]
Terminal font recognition for Tilix fails in r264:
![tilixtfbug](https://user-images.githubusercontent.com/82701459/118082978-68e61780-b3be-11eb-903f-e1f73bfe49e3.png)
As you can see, It works in r256.

Both system and custom font detection fails.

**Comment by DarNCelsius** [comment]
A lot of changes to `settings.c` between these versions. I suspect it's in the DConf implementation:
![tilixtfbug2](https://user-images.githubusercontent.com/82701459/118084177-8a480300-b3c0-11eb-8f6a-1ae3e2bc4f1c.png)

**Comment by LinusDierheimer** [comment]
You know better how the Tilix code works, can you try to fix it please?

**Comment by DarNCelsius** [comment]
It looks like this is NULL at line 60 in `settings.c`:
```C
    if(data->client == NULL)
        return FF_VARIANT_NULL;
```
Is DConf not loading properly?

**Comment by DarNCelsius** [comment]
Yup. Replacing this line:
```c
DynamicLibrary library = FF_LIBRARY_LOAD(instance->config.libDConf, "libdocnf.so", mutex);
```
with this from 256:
```c
    void* library = dlopen(instance->config.libDConf.length == 0 ? "libdconf.so" : instance->config.libDConf.chars, RTLD_LAZY);
    if(library == NULL)
    {
        pthread_mutex_unlock(&mutex);
        return FF_VARIANT_NULL;
    }
```
makes it work.
