### ISSUE TITLE
add support for armv7

### ISSUE THREAD

**Issue by Danik2343** [LinusDierheimer/fastfetch#390]
# Current state: build for armv7 not supported

# Wanted state: build for armv7 supported

# Why the change is sensible: add more arm architectures.

**Comment by LinusDierheimer** [comment]
Do you have a build output for me? C is supported on armv7, so theoretically it should work. If it is a minor issue i might be able to fix it without the need to set up a VM.

**Comment by CarterLi** [comment]
I just managed to compile all fastfetch code for armv7 (-m32) in my Android phone with vulkan support disabled (but link failed due to lack of armv7 libraties)

**Comment by Danik2343** [comment]
I am compiling on Samsung Galasy S5 (klte) on PostMarketOS Edge.

**Comment by CarterLi** [comment]
What were the errors printed?

**Comment by Danik2343** [comment]
/usr/bin/cc broken

**Comment by Danik2343** [comment]
GCC installed

**Comment by LinusDierheimer** [comment]
Try reinstalling gcc and gcc-libs

**Comment by Danik2343** [comment]
I installed build-base package, fixed! Thanks!
