### ISSUE TITLE
Reading SSID (and more Wifi information) on Linux

### ISSUE THREAD

**Issue by RainerKuemmerle** [LinusDierheimer/fastfetch#394]
# Current state:
dev branch seems to run iw command to parse information about wifi on Linux.

# Wanted state:
Do not launch a program to parse wifi information.

# Why the change is sensible:
iw is not always installed and would be a further requirement to retrieve the information.
Furthermore, starting a command and parsing its output contradicts being fast.

https://github.com/RainerKuemmerle/fastfetch/commit/80408df2d12a9f09f1cbd2ed5a393e3601e0c78c

In that commit I put a rough prototype based on an older HEAD to read SSID.
The other information was not of interest to me so far.
Since, I am not an expert with respect to the kernel API. What do you think about using the above approach for retrieving the information?

**Comment by CarterLi** [comment]
ioctls can get only SSID and mac address. We now use libnm instead.

**Comment by RainerKuemmerle** [comment]
Thanks for having such a quick look at the feature. I like the idea to use an existing/common library for this. Awesome!
I'll try later. On the weekend I ran into some issue with HEAD failing to parse my configuration file but I did not follow up on this yet.

**Comment by RainerKuemmerle** [comment]
Works as expected for me. Thanks.
