### ISSUE TITLE
Module CPU Temp

### ISSUE THREAD

**Issue by Zerogiven** [LinusDierheimer/fastfetch#398]
# Current state:
No module to show the CPU temp :-)

# Wanted state:
Module to show the CPU temp ;-)

# Why the change is sensible:
Just a feature which i'm missing here :1st_place_medal:

**Comment by CarterLi** [comment]
It is supported by fastfetch on Linux, macOS, and maybe FreeBSD (I say maybe because no one tested that), but is disabled by default as requested by the original auther.

Enable it with `--cpu-temp`

There are other `--*-temp`, but work only on  macOS

**Comment by CarterLi** [comment]
git head works for me

![image](https://user-images.githubusercontent.com/6134068/213721995-43878ca1-1eb6-42e0-ae76-5b0972d72b0c.png)

**Comment by Zerogiven** [comment]
Yes now i see it too, got a configuration mismatch (again -.-)... others are, like you have said, not showing but that's ok :+1:
