### ISSUE TITLE
GLIBC error on Debian Stable 

### ISSUE THREAD

**Issue by sbstn87** [LinusDierheimer/fastfetch#407]
Hi,

after installing the latest version of fastfetch (1.9.1) from the provided ,deb package, I cannot run it on MX Linux, which basically Debian Stable (11, bullseye).

The error I get:
fastfetch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by fastfetch)
fastfetch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by fastfetch)

Is it possible to build the .deb package in a way that makes it compatible with Debian Stable?

**Comment by LinusDierheimer** [comment]
@CarterLi what do you think about statically linking glibc for prebuild binaries?

**Comment by CarterLi** [comment]
glibc is Linux specific. You may do what you want.

**Comment by sbstn87** [comment]
I have installed the .deb package and now it works. 

Thank you.
