### ISSUE TITLE
Get IP6 address as placeholder

### ISSUE THREAD

**Issue by Zerogiven** [LinusDierheimer/fastfetch#408]
# Current state:
IP4 and IP6 addresses have both their own lines

# Wanted state:
Show IP4 and IP6 address in one line :)

# Why the change is sensible:
I want to get a more compact style but not with less informations ;)

**Comment by CarterLi** [comment]
Please try dev HEAD

![WX20230202-175434@2x](https://user-images.githubusercontent.com/6134068/216292361-69b8a184-838f-4bda-bb0b-76f5276c31ce.png)

**Comment by Zerogiven** [comment]
Pretty nice :)

```bash
❯ ./fastfetch --structure LocalIP --localip-show-ipv6 --localip-compact-type default --disable-linewrap false --localip-name-prefix wl
             ...-:::::-...                  Local IP: 192.168.51.34 fe80::ff9e:3c17:6bdb:826c
          .-MMMMMMMMMMMMMMM-.    
      .-MMMM`..-:::::::-..`MMMM-.    
    .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.    
   -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-    
 `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`    
 :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:    
.MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.    
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:    
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:    
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:    
.MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.    
 :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:    
  :MMM:MMM:`                `:MMM:MMM:    
   .MMM.MMMM:--------------:MMMM.MMM.    
     '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'    
       '.-MMMM``--:::::--``MMMM-.'    
            '-MMMMMMMMMMMMM-'    
               ``-:::::-``    

```

I'm not sure if it's helpful printing the adapter name aside the ip :question: 
xxx.xxx.xxx.xxx(XXX) for example...

**Comment by CarterLi** [comment]
I don't think one-line mode is useful without `--localip-name-prefix`. But I have an another idea.

**Comment by CarterLi** [comment]
![image](https://user-images.githubusercontent.com/6134068/216352677-0e7018db-76a0-4ee3-84f4-c15f82378f6e.png)

**Comment by Zerogiven** [comment]
Not sure what do you think about but i like it :smile:
