### ISSUE TITLE
Feature request, display GPU total vram and used vram.

### ISSUE THREAD

**Issue by Samueru-sama** [LinusDierheimer/fastfetch#416]
It would be nice to have that info displayed by fastfetch, I launch fastfetch along with htop with one single keybind, that way I can see almost all system information, the only thing missing of this combination is the vram of the GPU.

I also have a conky to display GPU info and the script uses this to display the info my nvidia gpu: nvidia-smi | awk 'FNR == 10 {print $13" - "$3" - "$9" / "$11; exit}'

It prints the GPU usage, temperature and vram, although the only thing that I'm interested here is just the vram usage, maybe something similar could be implemented to fastfetch, I don't know how difficult it would be.

**Comment by CarterLi** [comment]
VMEM detection is now supported with `--gpu-force-vulkan --allow-slow-operations`
