### ISSUE TITLE
GLIBC error on Ubuntu 20.04

### ISSUE THREAD

**Issue by jahway603** [LinusDierheimer/fastfetch#420]
Same Issue as Issue https://github.com/LinusDierheimer/fastfetch/issues/407 but on Ubuntu 20.04. It's a server and trying to wget the link you shared in Issue https://github.com/LinusDierheimer/fastfetch/issues/407 does not work.

**Comment by CarterLi** [comment]
Linux binary should be static-linked with musl, or similar issues never stop.

**Comment by LinusDierheimer** [comment]
This is a different issue. GLIBC is backwards compatible, so building against an older version shouldn't be a trouble.
In #407 the deb package was built on Ubuntu 20.04, which ships a newer version than debian stable, hence the issue. As a response, i changed the Ubuntu version for building the deb to 18.04, which ships an older version.
More interesting, to the time this issue arrived, the deb from the release tab was still built on Ubuntu 20.04, the exact same OS this issue appeared on. Both the binary from 18.04 and 20.04 should work here.

@jahway603 Can you please post all the output you get?

**Comment by jahway603** [comment]
@LinusDierheimer just tested the version 1.10.3 deb pkg on 2 Ubuntu 20.04 systems and they both ran it successfully. Closing this issue as it's now resolved.
