### ISSUE TITLE
musl aarch64 compilation error

### ISSUE THREAD

**Issue by Matthieu-Sauer** [LinusDierheimer/fastfetch#429]
# General description of bug:

Project fails to compile on Void linux ARM musl version (I build it with clang and none of the optional dependencies.)
`fastfetch/src/detection/wifi/wifi_linux.c:250:32: error: use of undeclared identifier 'caddr_t'`

This is due to caddr_t being (in musl) in the file "sys/types.h" which seems not to be included.

I included it locally and it did solve the compilation issue.

**Comment by CarterLi** [comment]
Done
