### ISSUE TITLE
[feature] Show editor settings

### ISSUE THREAD

**Issue by m-ildefons** [LinusDierheimer/fastfetch#430]
# Current state:

Default editor settings are completely ignored and it is impossible to show them in the output.

# Wanted state:

On Platform that support it, e.g. Linux, FreeBSD and MacOS, the environment variables `$VISUAL` and `$EDITOR` can be queried to fetch the configured default visual and/or line editor. On modern systems where line editors are rarely used, the distinction less important. But the environment variables may still be used to communicate which editor should be referred to to programs, e.g. https://github.com/git/git/blob/master/editor.c.

Work in progress sample:
![fastfetch](https://user-images.githubusercontent.com/17141774/223483904-cd846f4f-b68e-4a5d-a7e8-0315ce8670ce.png)

# Why the change is sensible:

Many users of fetching programs like this and the unfortunately unmaintained `neofetch` are happy to show off their individual choice of software. This includes the editor, especially in case of command line editors like `nano` and `neovim`, which integrate deeply with other system programs like command line email clients, git and more via system mechanisms.
This feature would allow users to show off their choice of editor along the other system configurations like window managers, shells and terminal emulators.

**Comment by CarterLi** [comment]
Try `fastfetch -s command --command-key Editor --command-text '$EDITOR -v | head -1'`

**Comment by CarterLi** [comment]
I doubt if I want to support this. There are other settings ( eg compiler version, pager version ) that are as easy as `command -v`. If we add all of these, it would be boring.

**Comment by LinusDierheimer** [comment]
ENV vars can be read much faster than opening a shell, maybe we can do something similar to command just for env:
```
fastfetch -s env --env-key Editor --env-text EDITOR
```
Maybe a 2.0 thing.

If the version is desired, i think command is the way to go too.

**Comment by CarterLi** [comment]
Please use Command module

**Comment by mhalano** [comment]
I think we could consider this. I use hyfetch and it has a module for it. I know I could just use the command module, but I think the easier the better. What do you think?

**Comment by CarterLi** [comment]
Fixed in dev branch

**Comment by mhalano** [comment]
Tested the 2.13.2 release from Ubuntu PPA and worked better than I expected. I thought it would just have `nvim` but also has the version.
Thanks for this feature.
