### ISSUE TITLE
Terminal font support for foot terminal

### ISSUE THREAD

**Issue by milkknife** [LinusDierheimer/fastfetch#431]
# Current state:
fastfetch does not have support for detecting terminal font for foot terminal
# Wanted state:
for fastfetch to have support for detecting terminal font for foot terminal
# Why the change is sensible:
this feature is available for every other terminal

- [terminal fonts/support status](https://github.com/LinusDierheimer/fastfetch#terminal-fonts)
- [foot terminal](https://codeberg.org/dnkl/foot)

The [config file](https://codeberg.org/dnkl/foot/src/branch/master/foot.ini) is `~/.config/foot/foot.ini` and the default value is `font=monospace:size=8` in a single line. The config file can have comments starting with `#`.

**Comment by CarterLi** [comment]
[Done](https://github.com/LinusDierheimer/fastfetch/commit/bdd9d46517ccb07145b147c654a839655045b234)

The config can be complex. I use the first font only for now. Also the font size `8` seems too small, but I print as it is.
