### ISSUE TITLE
[Feature request] Release ARM64 (such as for Raspberry Pi) binaries

### ISSUE THREAD

**Issue by jahway603** [LinusDierheimer/fastfetch#434]
# Current state: No ARM64 binaries

# Wanted state: Please release ARM64 binaries

# Why the change is sensible: People run Linux servers on Raspberry Pi type systems.

**Comment by CarterLi** [comment]
No. fastfetch uses Github Actions to build binaries but GitHub Actions don't provide Linux arm64 build images.

See https://github.com/actions/runner-images/issues/5631

**Comment by jahway603** [comment]
Does that mean ARM64 binaries will appear once https://github.com/actions/runner-images/issues/5631 is complete?

**Comment by CarterLi** [comment]
Yes. You may reopen this issue when it is fixed.

**Comment by shawaj** [comment]
Can you not just cross-compile using docker/setup-qemu-action?
