### ISSUE TITLE
[Feature Request] fastfetch should also detect user installed flatpaks as well.

### ISSUE THREAD

**Issue by dnkmmr69420** [LinusDierheimer/fastfetch#436]
# Current state: I have noticed that fastfetch does not detect flatpaks installed in ~/.var/app and only in /var/lib/flatpak

# Wanted state: fastfetch should list the number of system wide flatpaks as "system-flatpaks" and list the number user wide flatpaks as "user-flatpaks"

# Why the change is sensible: Because it will let me know how many user wide flatpaks are installed

**Comment by dnkmmr69420** [comment]
ah thanks for adding my suggest feature

**Comment by mateowoetam** [comment]
with this change, how do I edit the config file if I only want to know the total and not the separate user/system packages?
