### ISSUE TITLE
A nix package for fastfetch

### ISSUE THREAD

**Issue by dnkmmr69420** [LinusDierheimer/fastfetch#438]
# Current state: There is no nix flake for fastfetch

# Wanted state: There should be a nix flake for fastfetch so it can be installed on more distros

# Why the change is sensible: So more people can have access to fastfetch since nix can be installed on almost any linux distro.

**Comment by LinusDierheimer** [comment]
This must be handled by nix itself. There is an open pull request: https://github.com/NixOS/nixpkgs/pull/176819. Your best bet is to update it. I lack the knowledge in nix to do it.
I can't provide a nix package through github releases, since cpack doesn't support building it.
