### ISSUE TITLE
Can not set both key and value

### ISSUE THREAD

**Issue by Likeny3** [LinusDierheimer/fastfetch#440]
# General description of bug:

It is not possible to change both the key of a module and the value of it.
For example setting both `--CPU-key "somethingelse"` and `--set CPU=somethingelse` only results in `CPU: somethingelse`.

* Does the issue occur across multiple terminal emulators? Y
* Does the issue occur across multiple shells? Y (pwsh, cmd)

Output of `fastfetch --version`:
```
fastfetch 1.11.0 (x86_64)
```

Output of `fastfetch --load-config devinfo`:
```
Error: couldn't find config: devinfo
```

Output of `fastfetch --load-config devinfo-verbose`:
```
Error: couldn't find config: devinfo-verbose
```

Output of `fastfetch --list-features`:
```
threads
vulkan
zlib
opencl
libcjson
```

**Comment by CarterLi** [comment]
`./fastfetch -s cpu --cpu-key abc --cpu-format def`
