### ISSUE TITLE
4 GPUs (2 duplicate) shown sometimes due to 2 Vulkan driver options

### ISSUE THREAD

**Issue by jmcelroy01** [LinusDierheimer/fastfetch#456]
# General description of bug:

The 2022 Zephyrus G14 has an iGPU and dGPU. When running fastfetch under 2 conditions, I get duplicate GPU entries: 

![image](https://github.com/LinusDierheimer/fastfetch/assets/59029169/7220bdc8-5a43-4b28-a4db-61bc5ebfea96)

Originally I got this result when running fastfetch with default options but without having built it with pci support. After rebuilding with pci, I got this:

![image](https://github.com/LinusDierheimer/fastfetch/assets/59029169/75c1c2ec-8ab4-4b5b-a3f5-6184436fe9f7)

_except_ when passing the --gpu-force-vulkan option, in which case it gave the same output as when built without pci. It is likely from having both `amd_pro_icd64.json` and `radeon_icd.x86_64` in `/usr/share/vulkan/icd.d/`, from having installed both mesa and amdgpu-pro-vulkan. 

If there was a way for it to show the total GPU memory without duplicates regardless of using --gpu-force-vulkan or not, that would be neat. I didn't see a toggle for displaying GPU memory or not in the options available to put in the config file. It would also be cool to be able to display amdgpu-pro-vulkan driver info in addition to Mesa, since those can be switched between ([link](https://wiki.gentoo.org/wiki/AMDGPU-PRO#Use_AMDGPU-PRO_Vulkan_drivers_for_specific_games)), and it seems to not know what the driver is when pointing to amdgpu-pro-vulkan (see below). Thanks!

Output of `fastfetch --version`:
```
fastfetch 1.11.0 (x86_64)
```

(relevant) Output of `fastfetch --load-config devinfo-verbose`:
```
OS: Gentoo x86_64
Host: ROG Zephyrus G14
Kernel: 6.1.27-gentoo-r1-x86_64
WM: Process name: Hyprland; Pretty name: Hyprland; Protocol: Wayland
Terminal: alacritty
GPU 1: Vendor: AMD; Name: AMD Radeon Graphics (RADV REMBRANDT); Driver: Mesa 23.1.0; Temperature: -nan; CoreCount: -1; Type: Integrated
GPU 2: Vendor: AMD; Name: AMD Radeon RX 6700S (RADV NAVI23); Driver: Mesa 23.1.0; Temperature: -nan; CoreCount: -1; Type: Discrete
GPU 3: Vendor: AMD; Name: AMD Radeon RX 6700S; Driver: ; Temperature: -nan; CoreCount: -1; Type: Discrete
GPU 4: Vendor: AMD; Name: AMD Radeon Graphics; Driver: ; Temperature: -nan; CoreCount: -1; Type: Integrated
Vulkan: driver: radv [Mesa 23.1.0]; Api Version: 1.3.243; Conformance Version: 1.3
```

Output of `fastfetch --list-features`:

Before rebuild
```
threads
vulkan
wayland
xcb-randr
xcb
x11
dbus
sqlite3
egl
glx
libpulse
```

After rebuild
```
threads
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
sqlite3
egl
glx
osmesa
opencl
libpulse
```

**Comment by CarterLi** [comment]
There is VkPhysicalDeviceProperties::deviceID. I'm not sure if it's useful.

**Comment by CarterLi** [comment]
Can you test the latest dev branch please?

**Comment by LinusDierheimer** [comment]
Tested it with radv and amdvlk and the fix does work for me
