### ISSUE TITLE
Ability to set vertical alignment

### ISSUE THREAD

**Issue by devferret** [LinusDierheimer/fastfetch#458]
# Current state:
<img width="500" alt="Screenshot 2023-05-25 at 4 53 23 PM" src="https://github.com/LinusDierheimer/fastfetch/assets/11474150/0d6e81d1-6b5f-4e88-878f-bc09fefd42cf">

The text is aligned to the top.

# Wanted state:
<img width="500" alt="Screenshot 2023-05-25 at 4 55 50 PM" src="https://github.com/LinusDierheimer/fastfetch/assets/11474150/8f4bf784-ba81-4533-b627-30cc5a59c921">
<img width="500" alt="Screenshot 2023-05-25 at 4 58 23 PM" src="https://github.com/LinusDierheimer/fastfetch/assets/11474150/54c97eaa-e794-4b52-8aa5-dbf2d2206771">

It would be nice to have the option to align the text or logo to center or bottom as well.

# Why the change is sensible:

It looks better if it's centered.

<img width="500" alt="Screenshot 2023-05-25 at 5 01 04 PM" src="https://github.com/LinusDierheimer/fastfetch/assets/11474150/e609dffa-a12f-448a-b211-9ce05df515c0">

For smaller logos, I set the structure option to make the text fit.

But macOS doesn't offer small logos, so it would be nice to have that option.

**Comment by LinusDierheimer** [comment]
Wanted state 1 can be done using `break` modules at the start of the structure.
Wanted state 2 can be done using the `--logo-padding-top` option.

**Comment by CarterLi** [comment]
Added macOS small logos

<img width="546" alt="image" src="https://github.com/LinusDierheimer/fastfetch/assets/6134068/8746ff12-8678-40c7-9b50-271fa76eda3f">

<img width="535" alt="image" src="https://github.com/LinusDierheimer/fastfetch/assets/6134068/6735c892-f5d9-493f-8bc4-1fda6f1e856c">
