### ISSUE TITLE
Problem with update and organization (Please Help)

### ISSUE THREAD

**Issue by Ellef06** [LinusDierheimer/fastfetch#460]
Has Windows 10 N (Norwegian) Version 1909
My machine is managed by the organization. It's there a possibility to remove organization.?
Can't get updated my Windows at all.
If I download an update or full version I don't get it installed as it says I can't update to USB. Have tried updating from the computer as well as from USB and DVD. Same message every time.
Is there somebody who can help me.
Thanks in advance.
Regards Ellef Ringnes
Email: ellef06@gmail.com

**Comment by CarterLi** [comment]
This is the place to disscuss issues or feature requests of fastfetch.

For other questions, you may ask on stackoverflow or somewhere else.
