### ISSUE TITLE
Make a way for us to compile without cmake

### ISSUE THREAD

**Issue by Alleop5** [LinusDierheimer/fastfetch#470]
# Current state

No way to do it easily

# Wanted state

Just add a Makefile that doesn't include any cmake specific stuff

# Why the change is sensible

CMake shouldn't be a required library. If I would for example want to add AutoPGO for myself. I would need to completely understand CMake. Which is way more complicated than it needs to be. [Also. the Suckless orginisation thinks cmake sucks](https://suckless.org/sucks).

**Comment by CarterLi** [comment]
`cmake .. -G "Unix Makefiles"` and you are done.

PS: According to the link, both GCC and clang suck. There are nothing to use.

**Comment by Alleop5** [comment]
They do have alternatives. But anyway I was talking about cc not gcc as cc is linked to your default compiler. Also cmake .. -G "Unix Makefiles". Uses. You got it. Cmake. And even if you included the output of cmake .. -G "Unix Makefiles" in the source code by default. It still calls CMake to actually compile it... Also the link isn't that important. Just to prove the point that CMake sucks. Really bad. It's the worst offender on the list. And this is supposed to be a fast. Kind of suckless alternative to neofetch. So it would make sense to atleast not use CMake.

What's even the reason for using CMake? It just makes every program hard to understand. And you could probably need to rewrite like 5 lines of code to fix it. I just can't understand C that much. As I don't know which source code file I need to compile to get it done.

**Comment by LinusDierheimer** [comment]
https://stackoverflow.com/questions/40083642/why-do-we-need-cmake

We support a lot of platforms, operating systems and even more optional features and compile time options. Doing that without a proper build system is impossible.

The only alternative i know of that can do that is meson, but it doesn't even can generate makefiles, so i guess it sucks too.

**Comment by Alleop5** [comment]
OK I can understand that. Just. Give us an option on Linux. Include a proper Makefile that properly executes cc with the right flags to let it compile. You can include CMake and a Makefile at the same time. I do realize now that this is a pretty huge codebase. Though I know Makefiles are basically shell scripts. So if you know shell scripts well enough. It should be easier than making CMake files.

**Comment by LinusDierheimer** [comment]
Writing a Makefile for Linux that will support everything needed, will probably be at least 5000 lines of code. Even if written once, maintaining this parallel to cmake is not an option.

> Though I know Makefiles are basically shell scripts. So if you know shell scripts well enough. It should be easier than making CMake files.

Thats just not true...

**Comment by CarterLi** [comment]
I honestly think meson is a better selection than CMake. The syntax of CMakeList is really not my thing. In addition, CMake is extremely slow on WSL; it take minutes to generate.

However, switching to Makefiles is a big no. Closing as not planned.

**Comment by Alleop5** [comment]
Yeah, I get it. Switching to meson should be good enough.

**Comment by eli-schwartz** [comment]
> CMake shouldn't be a required library. If I would for example want to add AutoPGO for myself. I would need to completely understand CMake. Which is way more complicated than it needs to be.

I can't find any references to "AutoPGO" on the internet, am I missing something?

> We support a lot of platforms, operating systems and even more optional features and compile time options. Doing that without a proper build system is impossible.

Well no wonder suckmore software thinks that proper build systems suck. :) They also think that optional features and compile time options suck compared to the, um, "beauty", of expecting end users to edit a raw header file to enable program options.

They don't just hate cmake either, they apparently hate both waf and scons for the indignity of requiring *python* to be installed, as opposed to proper reasons like requiring you write your own build system in python after importing waf/scons as a library, then failing to get proper target abstractions, on top of being really slow.

(And meson is also written in python, oh no.)
