### ISSUE TITLE
Distribution support

### ISSUE THREAD

**Issue by saloniamatteo** [LinusDierheimer/fastfetch#5]
(This is not an issue; referring to commit dd19fcf)

Just wanted to let you know, `fastfetch` actually works on Debian!
The only dependencies I had to install were: `cmake libxrandr-dev libpci-dev`

Here's a screenshot from my VM:

![debian](https://user-images.githubusercontent.com/28765699/111862217-cd9b6d80-894b-11eb-9408-bddbb05394a7.png)

**Comment by LinusDierheimer** [comment]
Thanks for letting me know. I think ill keep this open so others can comment on support / problems on various distributions. Interesting is that locale doesn't work as i thought /etc/locale.conf was common among all major distributions.

**Comment by saloniamatteo** [comment]
Digging into this, Debian indeed does not have `/etc/locale.conf`. However, I suggest to check the following environment variables, as a fallback:

- `LC_ALL`
- If the above is undefined/blank, try `LC_CTYPE` and/or `LC_MESSAGES`

So, the order would be:
1. `/etc/locale.conf`
2. `LC_ALL`
3. `LC_CTYPE`
4. `LC_MESSAGES`

Going further than this would mean that the distro does not have sane defaults and/or the configuration wasn't done properly.

**Comment by saloniamatteo** [comment]
An initial implementation of the above was made with PR #7
