### ISSUE TITLE
LXQt Mutter fail

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#55]
Using Mutter as WM on LXQt fails:
![lxqtmutter](https://user-images.githubusercontent.com/82701459/119032157-26b76a00-b9ac-11eb-9839-d94ccfb170c3.png)

![mutter](https://user-images.githubusercontent.com/82701459/119032704-c543cb00-b9ac-11eb-908f-16104f3e75cb.png)
User configured WM would be in .config/lxqt/session.conf
```ini
[General]
__userfile__=true
window_manager=openbox
```

**Comment by DarNCelsius** [comment]
This is with r318:
![lxqtmutter2](https://user-images.githubusercontent.com/82701459/119271620-99218780-bc02-11eb-8ea6-a95d72ff9774.png)

**Comment by LinusDierheimer** [comment]
What probably happens is following:
* Mutter detection by process fails
* XDG_*_DESKTOP is set as WM, it falls back to process detection for DE
* LXQT detection by process succeeds
* DE is set to LXQT

So we have two issues here:
1) Mutter WM detection
2) Setting the WM to XDG_*_DESKTOP if it contains a known DE

Looking into both, any help appreciated.

**Comment by DarNCelsius** [comment]
```sh
╰─ echo $XDG_SESSION_DESKTOP
LXQt Desktop

╭─    ~                                                                                                                                                                                                                                                               ✔  20:17:25  
╰─ echo $XDG_CURRENT_DESKTOP
LXQt
```

**Comment by DarNCelsius** [comment]
You're not checking for mutter in detectWMDE.c - you're checking for 'gnome-session-binary'. Might wanna extend that search if LXQt is running. Parsing session.conf seems the quickest way.
I'm not sure of the default state of that file - Openbox is the default WM for LXQt out of the box though.

**Comment by LinusDierheimer** [comment]
Yes extending the search is the right way. This will fix issue number one and two on setups with known WMs.

Once we fixed issue two we can check if `wmPrettyName` is empty in `getLXQt` and parse this file to get the WM.

**Comment by LinusDierheimer** [comment]
Pushed the fix.

**Comment by DarNCelsius** [comment]
That was quick :grinning: 
![lxqtmutter3](https://user-images.githubusercontent.com/82701459/119272644-43031300-bc07-11eb-80d2-e31e66ae2ee7.png)

**Comment by LinusDierheimer** [comment]
Is the WM Theme still right? Currently i simply print the GTK theme for mutter if it is not running in a Gnome session. Is this the correct behavior?

**Comment by LinusDierheimer** [comment]
Also the output of `fastfetch --terminal-font-format {}` would be interesting.

**Comment by DarNCelsius** [comment]
Yes. The window manager handles the WM themes in LXQt.

![lxqtmutter4](https://user-images.githubusercontent.com/82701459/119272825-434fde00-bc08-11eb-8fa3-93893d9f712b.png)
Seems to be the old format.

**Comment by LinusDierheimer** [comment]
Thanks i was just wondering if the font is just named Monospace (which is a bad name for a font tbh because it also is a font type) or if i am cutting something important of.

**Comment by DarNCelsius** [comment]
The font name is a substitution. It's really 'Deja Vu Sans Mono Book 10'
