### ISSUE TITLE
Mutter WM theme wrong on Budgie

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#56]
On Budgie desktop, the Mutter WM Theme is wrong. There's nothing using Arc-Dark on my system.
![budgiewmtheme](https://user-images.githubusercontent.com/82701459/119042256-dfcf7180-b9b7-11eb-9146-6868b7ce16d7.png)
Dconf editor shows the key used as being deprecated. The theme being used is Matcha-Dark-Azul.

**Comment by DarNCelsius** [comment]
Here's a comment from the Budgie dev on Mutter themes:
https://github.com/dylanaraps/neofetch/issues/408#issuecomment-258986472
So basically the same as GTK theme, or nothing at all.

**Comment by LinusDierheimer** [comment]
Should work with latest commit. Close this on confirm.

**Comment by DarNCelsius** [comment]
Looks good :+1:

**Comment by DarNCelsius** [comment]
You should probably still rewrite printMutter().
"/org/gnome/desktop/wm/preferences/theme" is not in use, and I think "/org/gnome/shell/extensions/user-theme/name" is only there with certain extensions. It certainly didn't exist when I tried Gnome.
I think it's just GTK in that case.

**Comment by LinusDierheimer** [comment]
I copied this directly from neofetch:
```bash
wm_theme=$(gsettings get org.gnome.shell.extensions.user-theme name)
[[ ${wm_theme//\'} ]] || \
    wm_theme=$(gsettings get org.gnome.desktop.wm.preferences theme)
```
There is an official extension "user theme" which allows custom theming of the shell, so we check that first.

**Comment by DarNCelsius** [comment]
I think so - that's the Gnome default.
You'd have to be running a _very_ old install if "org.gnome.desktop.wm.preferences theme" exists though.
