### ISSUE TITLE
Incorrect display of installed snap packages

### ISSUE THREAD

**Issue by FrankBG67** [LinusDierheimer/fastfetch#59]
> OS: Manjaro Linux (x86_64)
Host: System Product Name System Version
Kernel: 5.12.8-1-MANJARO
Uptime: 1 day, 23 hours, 2 mins
Packages: 1440 (pacman)[stable], 3 (flatpak), 1 (snap)
Shell: bash 5.1.8

> [fbg@main ~]$ snap list
No snaps are installed yet. Try 'snap install hello-world'.

In fastfetcht it shows that 1 snap package is installed. This is incorrect.
This is my 1st reported issue. If I have made a mistake, please ignore it.

**Comment by LinusDierheimer** [comment]
What is the output of `ls /snap`?

**Comment by FrankBG67** [comment]
> Permissions Size User Date Modified Name
drwxr-xr-x     - root 24 Apr 13:44  bin
.r--r--r--   590 root  6 Jun 07:52  README

**Comment by LinusDierheimer** [comment]
Pushed a fix.
