### ISSUE TITLE
Fastfetch is not working with smaller terminal windows.

### ISSUE THREAD

**Issue by wizard-28** [LinusDierheimer/fastfetch#61]
I use a Tiling WM (Sway), so most of the time my windows open in 50% space. When I try to run `fastfetch` this way, the whole output gets messed up.
![fastfetch](https://0x0.st/-L_y.png)

But when I run `neofetch` in this window, the output scales correctly.
![neofetch](https://0x0.st/-L_t.png)

**Comment by LinusDierheimer** [comment]
With scaled correctly, you probably mean not overflowing / cut (depending on the terminal emulator). This behavior is forced by printing the `\033[7h` ascii escape sequence. It is disabled by printing `\033[7l`. However, i want to ensure that the disable sequence is always printed on exit, so this is a a bit of work, but definitely on my TODO list, so will come soon!

**Comment by LinusDierheimer** [comment]
Should be working with latest commit. Close this on confirm.

**Comment by wizard-28** [comment]
Yes, it's working!
