### ISSUE TITLE
Setup automatic code reviews

### ISSUE THREAD

**Issue by wizard-28** [LinusDierheimer/fastfetch#64]
Setting up automatic code reviews will improve the code quality of this project, and give valuable suggestions in the future.

Try using [Codacy](https://www.codacy.com/) [More features but slower reviews, around 1.5 mins] or [CodeFactor](https://www.codefactor.io/) (Less features but faster reviews, around 2 secs)

**Comment by LinusDierheimer** [comment]
TBH i don't think this is something worth it right now. Fastfetch is too small and changing too rapidly, and i don't wan't to focus on something like this, as i develop only in my free time. Maybe in the future.

**Comment by wizard-28** [comment]
It's supposed to be automatic, you don't have to sit and configure anything, just click buttons once, and it'll work automatically forever.

**Comment by wizard-28** [comment]
If you write quality code from the beginning, then in the future it'll help in the development of the project, as more people will be encouraged to contribute to it.
