### ISSUE TITLE
Add Pacstall installation method to the Packaging section

### ISSUE THREAD

**Issue by wizard-28** [LinusDierheimer/fastfetch#66]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. I am the maintainer (and also one of the developers of Pacstall) of the [fastfetch-git](https://github.com/pacstall/pacstall-programs/blob/master/packages/fastfetch-git/fastfetch-git.pacscript) pacscript in this [repository](https://github.com/pacstall/pacstall-programs).

It can be installed on Ubuntu by running this command (After Pacstall is installed)
```bash
sudo pacstall -I fastfetch-git
```

---

It can also be upgraded
```bash
sudo pacstall -Up
```
and removed when requested.
```
sudo pacstall -R fastfetch-git
```
---

This clones the git repo, builds and installs every file in the right directory (auto completions, binaries, license and the README) automatically.

So, can you add this installation method in the README.md for Ubuntu?

*PS: In the next release of Pacstall, we are actually removing the need of running `pacstall` with `sudo`, so the commands will change. We are expecting to release the next version by Thursday.*

**Comment by wizard-28** [comment]
I briefly mentioned the installation script in #60 in this [comment](https://github.com/LinusDierheimer/fastfetch/issues/60#issuecomment-861215564)

**Comment by LinusDierheimer** [comment]
I don't want to add specific installation instructions for each package manager, as this would be very redundant and bloat the README.

**Comment by LinusDierheimer** [comment]
Also in packaging section i only mention the very big repositories used by a lot of people, for example garuda, which package fastfetch too, is missing from there.

**Comment by wizard-28** [comment]
Makes sense, thanks for listening!
