### ISSUE TITLE
Strange KWin WMTheme output

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#67]
![wmthemekwin](https://user-images.githubusercontent.com/82701459/122669580-5da4b980-d1be-11eb-9e1e-ca8596e6fdd7.png)

**Comment by LinusDierheimer** [comment]
Content of `$XDG_CONFIG_HOME/kwinrc`?

**Comment by DarNCelsius** [comment]
`theme=__aurorae__svg__Nord-Aurorae`

So not a bug then I guess?

**Comment by LinusDierheimer** [comment]
Yes its your theme that is named weird
