### ISSUE TITLE
Plasma detections

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#68]
I see very strange results in Plasma:

```sh
DE: KDE Plasma 5.21.5
WM: KWin (X11)
WM Theme: __aurorae__svg__Nord-Aurorae
Theme: kvantum (NordDarkColor) [Plasma], Matcha-dark-azulMatcha-dark-azul [GTK2], Matcha-dark-azul [GTK3/4]
Icons: Breeze Chameleon Dark [Plasma], Breeze Chameleon DarkBreeze Chameleon Dark [GTK2], Breeze Chameleon Dark [GTK3/4]
Font: DejaVu Sans (9pt) [Plasma], DejaVu Sans 9Sans Serif (9pt) [GTK2], DejaVu Sans (9pt) [GTK3/4]
```
GTK2 values are doubled.

Matcha-dark-azul should be output for all GTK's.
Font and icons should be the same for everything.

**Comment by DarNCelsius** [comment]
This was not just on Plasma.
I don't know what caused the GTK2 values to be all over the place, but I ran lxappearance, and they all went normal again.
Might be worth while to figure out what caused the weird output though.

**Comment by DarNCelsius** [comment]
The Plasma and GTK fonts/cursors/icons are identical. Have you thought about consolidating them, i.e [Plasma/GTK2/3/4] ?
![plasma](https://user-images.githubusercontent.com/82701459/122683809-f27cd680-d201-11eb-99f1-e06b272ace9a.png)
As you can see, Cursor Theme is coming soon. :grinning:

**Comment by LinusDierheimer** [comment]
I just pushed cursor theme as i did that too. Oops

**Comment by LinusDierheimer** [comment]
While developing this i also found the cause for this issue: `ffGetPropValue` appends the value. So if it was set multiple in a file it was appended multiple times. Fixed with latest commit.

**Comment by DarNCelsius** [comment]
I've been using all sorts of different desktops setting these values lately, so one of those programs probably added more than it should.

I'll go test the new version. :)
