### ISSUE TITLE
Cursor Size not working

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#69]
Cursor size changes is not detected on LXQt, XFCE or Mate.
Plasma works. Is the size really in points though?

**Comment by DarNCelsius** [comment]
Correct schema for Mate should be
`org.mate.peripherals-mouse`
Paths should be 
`/org/mate/desktop/peripherals/mouse/cursor-size` and `/org/mate/desktop/peripherals/mouse/cursor-theme`

**Comment by LinusDierheimer** [comment]
This is the expected behavior, as i have only specifically implemented cursor for Plasma and XFCE. For all other DEs it falls back to plain GTK, which often doesn't reflect live changes. Feel free to open a PR for Mate.

**Comment by DarNCelsius** [comment]
I thought it was in pixels.
Anyway, XFCE does not show size changes either.

**Comment by LinusDierheimer** [comment]
Relevant line:
`ffSettingsGetXFConf(instance, "xsettings", "/Gtk/CursorThemeSize", FF_VARIANT_TYPE_INT).intValue`
If xfconf doesn't update size, i don't know of any other method for XFCE.
Pixels is also possible, will look into this.

**Comment by DarNCelsius** [comment]
![xfconf](https://user-images.githubusercontent.com/82701459/122687328-1ba76200-d216-11eb-810f-a31bdbb765a7.png)
![xfconf2](https://user-images.githubusercontent.com/82701459/122687330-1ea25280-d216-11eb-83be-23f3c18d743a.png)

**Comment by LinusDierheimer** [comment]
Found the bug and fixed it.

**Comment by DarNCelsius** [comment]
Yup.

**Comment by DarNCelsius** [comment]
[X11 XCursor](https://invisible-island.net/xterm/xcursor/xcursor.html)
XCURSOR_SIZE   This variable sets the desired cursor size, in pixels.

**Comment by LinusDierheimer** [comment]
Yea just read about that here: https://wiki.archlinux.org/title/Cursor_themes. Will change with next commit
