### ISSUE TITLE
Distribution request: CelOS

### ISSUE THREAD

**Issue by whyadamsalt** [LinusDierheimer/fastfetch#75]
output of /etc/os-release:

NAME="CelOS"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="CelOS 1-beta4"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Logo:
![image](https://user-images.githubusercontent.com/75907419/124402209-b9c31e00-dd26-11eb-9389-c970c74b6b2f.png)

**Comment by LinusDierheimer** [comment]
Im very happy to implement it, however there are some changes i need to do to the code before. For whatever reason the `ID` field still says `ubuntu`, and this is what fastfetch is currently using. 
The Logo shown differs from the one neofetch shows (`neofetch --ascii_distro CelOS`). Is the one you gave me more up to date?
Also which color to use as primary / key color? The logo you posted would suggest magenta, neofetch uses green.

**Comment by whyadamsalt** [comment]
The logo i've sent is more up to date and I can change the `ID` field in an upcoming version. Magenta would be a nice color for this to use!

**Comment by LinusDierheimer** [comment]
Done.
