### ISSUE TITLE
Thunar terminal open segfault

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#79]
Fastfetch segfaults when opening a terminal from Thunar:
![exobug](https://user-images.githubusercontent.com/82701459/125200491-c2a67900-e26b-11eb-9215-14c71a955c6e.png)
Command line:
`exo-open --working-directory %f --launch TerminalEmulator`

It works in PCManFM and PCManFM-Qt. I don't know the command line from those though

Subsequent fastfetch commands also segfaults at the same spot in that window.
Running `exo-open --launch TerminalEmulator` globally works fine.

**Comment by LinusDierheimer** [comment]
I tried to reproduce, but exo-open fails to find TerminalEmulator when installing only it. As i don't want to pull in the whole XFCE ecosystem, i leave this one for you. Most probably something in `/src/common/detectTerminalShell.c` or `src/common/packages.c`. Run with `--multithreading false` to see if it is the shell or the package code that crashes.

**Comment by LinusDierheimer** [comment]
Seems like an error in `src/common/detectWMDE.c`. Can you check that? Probably an error in XFCE specific code.

**Comment by LinusDierheimer** [comment]
Possible that sessionDesktop is somehow `NULL`? `applyPrettyNameIfWM` doesn't check for that even that case is possible, see this line (365):
```c
//If sessionDesktop is a known WM, set it.
applyPrettyNameIfWM(result, result->sessionDesktop, &protocolHint);
```
the check must be added anyway, similar to `applyPrettyNameIfDE`:
```c
if(name == NULL || *name == '\0')
    return;
```
If you open a PR, and this is not the error, you can include that fix too.

**Comment by DarNCelsius** [comment]
So there's definitely something weird going on with with terminal  detection when launched from Thunar.
Plasma/KWin:
![exobug3](https://user-images.githubusercontent.com/82701459/125501101-db5f04c1-8cf9-41e0-b26c-c2eecd04168d.png)
LXQt/Openbox:
![exobug4](https://user-images.githubusercontent.com/82701459/125501131-b238178d-ec21-4dc9-894d-26b15019b16e.png)
The only one that actually segfaullts is regular Openbox.

**Comment by DarNCelsius** [comment]
I added
```c
if(processName == NULL || *processName == '\0')
        return;
```
to the start of `applyPrettyNameIfWM` - no change.

That's what you meant, right?

**Comment by DarNCelsius** [comment]
Here's the process that's launched:
![exobug6](https://user-images.githubusercontent.com/82701459/125505267-e5c348a9-d619-47bc-a0bf-30bd8f888fdf.png)

**Comment by DarNCelsius** [comment]
The error output seems to know the terminal name at least:
![exobug7](https://user-images.githubusercontent.com/82701459/125506290-3719de63-798c-4e62-bb81-0d59cf65d760.png)

**Comment by DarNCelsius** [comment]
Turning off multithreading removes the random garbage on each run and leaves the line blank. I'm not sure where to go from here.

**Comment by LinusDierheimer** [comment]
Should be. However im still unable to reproduce, even in a VM with similar setup. This makes it hard to find the cause. Maybe use gdb too see where things go wrong?

**Comment by DarNCelsius** [comment]
In terminal.c,
```c
if(instance->config.terminalFormat.length == 0)
    {
        ffPrintLogoAndKey(instance, FF_TERMINAL_MODULE_NAME, 0, &instance->config.terminalKey);
      //  puts(result->terminalExeName);
      printf("\nresult->terminalProcessName: %s\nresult->terminalExe: %s\nresult->terminalExeName: %s\n", result->terminalProcessName.chars, result->terminalExe.chars, result->terminalExeName);
    }
```

![thunarTermExe](https://user-images.githubusercontent.com/82701459/126029600-fb27d6a9-3bdc-4dcb-a1a1-232d0dec0e58.png)
So `result->terminalExeName` is not valid for some reason.

Here's the terminal launched normally:
![thunarTermExe2](https://user-images.githubusercontent.com/82701459/126029710-98bf7f0f-ebe4-4873-be10-8eec63eff65e.png)

**Comment by DarNCelsius** [comment]
Fixed in #80.

No idea what that failure means though.

**Comment by LinusDierheimer** [comment]
Is it possible that your `terminalExe` ends with a slash at any point? This would fail then:
```c
uint32_t lastSlashIndex = ffStrbufLastIndexC(exe, '/');
if(lastSlashIndex < exe->length)
    *exeName = exe->chars + lastSlashIndex + 1;
```

**Comment by LinusDierheimer** [comment]
Inactive.
