### ISSUE TITLE
GPU value is displayed as "troller"

### ISSUE THREAD

**Issue by saloniamatteo** [LinusDierheimer/fastfetch#8]
![gpu](https://user-images.githubusercontent.com/28765699/112031526-5a545000-8b33-11eb-8c22-3fc2cdf9f10e.png)

**Comment by LinusDierheimer** [comment]
Can you please give me the gpu line(s) in the output of lspci?

**Comment by saloniamatteo** [comment]
Removing cached contents with `rm -rf ~/.cache/fastfetch` fixes this problem the next time the program is ran, but on the second execution, the issue comes back.

**Comment by LinusDierheimer** [comment]
So running with --recache gives the right result? Is troller a substring of the gpu name?

**Comment by saloniamatteo** [comment]
Just to be clear, here's a preview:

https://user-images.githubusercontent.com/28765699/112032502-5ecd3880-8b34-11eb-8ee2-fc98928eedf4.mp4

> So running with --recache gives the right result? Is troller a substring of the gpu name?

Yes, as shown in the video.

**Comment by LinusDierheimer** [comment]
Can you cat ~/.cache/fastfetch/GPU0 to look if the problem is saving or loading the cache?

**Comment by saloniamatteo** [comment]
`cat ~/.cache/fastfetch/GPU0` indeed shows "Intel Corporation 4th Gen Core Processor Integrated Graphics Controller", before and after running without recache.

**Comment by LinusDierheimer** [comment]
Thanks, i think the problem is that the string is longer than 64 bytes, which leads to FFstrbuf needing to resizes its capacity. Somehow the original 64 bytes seem to be discarded. I will take a look at this in around a hour. If you're interested the method is ffPrintCachedValue in src/common.c

**Comment by saloniamatteo** [comment]
Thanks, I'll look into it; if I fix the problem, I'll open a PR.

**Comment by saloniamatteo** [comment]
Opened PR #9, closing.

**Comment by LinusDierheimer** [comment]
Found the bug. From https://man7.org/linux/man-pages/man2/read.2.html: 
> On success, the number of bytes read is returned (zero indicates end of file), _and the file position is advanced by this number_.
So we need to rewind the file descriptor each time before we try reading with a larger buffer.
Additional we should call ffStrbufInitA to set a larger buffer in ffPrintCachedValue because i think cached values being larger than 64 bytes is a common thing. I will implement this soon.

**Comment by saloniamatteo** [comment]
OK. Now check PR #10: the file descriptor is correctly rewinded, compilation is successful, and no cache errors happen.

**Comment by saloniamatteo** [comment]
I have just noticed `fastfetch`, with this PR, displays the following:

`GPU0: Intel Corporation 4th Gen Core Processor Integrated Graphics Con`

Maybe we should increase the allocation value to `71` bytes (or higher),
because the text above is exactly `64` bytes (without counting `GPU0: `).

**Comment by LinusDierheimer** [comment]
Should work with commit https://github.com/LinusDierheimer/fastfetch/commit/02c450c218795baea1572237ac12e305d917635c. If you can confirm it works on your machine too i will close this

**Comment by saloniamatteo** [comment]
Yes, it does work.
