### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by AdisonCavani** [LinusDierheimer/fastfetch#83]
I have installed ``fastfetch`` from AUR on WSL2 (ArchLinux) and I'm getting "segmentation fault".
[Image](https://i.imgur.com/uXhuz3s.png)

**Comment by LinusDierheimer** [comment]
Its hard to tell where the problem is just from the image, as fastfetch is multi threaded and any of those threads may segfault. Use `fastfetch --multithreading false` and tell me where it does stop now.

**Comment by AdisonCavani** [comment]
error: XDG_RUNTIME_DIR not set in the environment.
[1]    4258 segmentation fault  fastfetch --multithreading false

**Comment by LinusDierheimer** [comment]
This is more complicated as it looks, as i never use `XDG_RUNTIME_DIR`. The question where it stops remains.

**Comment by LinusDierheimer** [comment]
This seems to be something specific with your setup, `XDG_RUNTIME_DIR= fastfetch` executes totally normal on my system, as it should. I don't have Windows installed so i can't test in WSL2. Without more information from you i can't do anything.

**Comment by AdisonCavani** [comment]
![error](https://user-images.githubusercontent.com/76855180/131338250-cc0c3778-4b1c-435d-9774-8b7caf14ebc5.png)
This is how it looks on my WSL2

**Comment by AdisonCavani** [comment]
After adding:
```
export XDG_RUNTIME_DIR=/some/directory/you/specify 
export RUNLEVEL=3
```
to .zshrc,
``XDG_RUNTIME_DIR not set in the environment`` is no longer visible, but I'm getting another error:

![error2](https://user-images.githubusercontent.com/76855180/131339156-c27cfff9-37fe-446a-9d22-66c1cbc18f11.png)

**Comment by LinusDierheimer** [comment]
Resolution seems to be the problem. Fastfetch first tries to use on of the libraries in specified order:
* `libwayland-client.so`
* `libXrandr.so`
* `libX11.so`

Most probably you have one of the X11 libraries installed as a dependency, but no X Server running. This isn't a problem on linux, as i have implemented and tested this scenario, but maybe WSL2 behaves different. Can you look which of those libraries are present?

If resolution detection fails for all three, fastfetch falls back to scanning `/sys/class/drm/*/modes` itself. But this surely doesn't need `XDG_RUNTIME_DIR`, so the error is most probably in some X Configuration.

**Comment by AdisonCavani** [comment]
![libs](https://user-images.githubusercontent.com/76855180/131385550-7e1c2a83-7648-48cc-9a65-f3f9f811ed87.png)

I've got this three libraries installed, but I don't have got ``/sys/class/drm/*modes``:

![sys](https://user-images.githubusercontent.com/76855180/131385736-4cfc89d9-5233-4262-9a5f-de10f23e7687.png)

**Comment by LinusDierheimer** [comment]
I assume you are compiling for yourself, so this shouldn't be much of a problem:

Go to the bottom of `src/modules/resolution.c`. You'll find the following function there:

```c
void ffPrintResolution(FFinstance* instance)
{
    if(
        printResolutionWaylandBackend(instance) ||
        printResolutionXrandrBackend(instance) ||
        printResolutionX11Backend(instance)
    ) return;

    printResolutionDRMBackend(instance);
}
```

Each `printResolution*` line calls a resolution implementation. Use comments (start the line with `//`) to disable them one by one. This way you can find out which implementation fails. Sorry for the extra work.

**Comment by AdisonCavani** [comment]
After commenting out first ``printResolution*`` should I uncomment first, and comment second or should I comment first, comment second and comment third?

**Comment by LinusDierheimer** [comment]
Keep the previous line commented, so it surely starts with the implementation to test.

**Comment by AdisonCavani** [comment]
First commented:

![2](https://user-images.githubusercontent.com/76855180/131389578-6a8afa81-0dd8-4b9a-97bf-9b3533a7c47d.png)

Second commented:

![3](https://user-images.githubusercontent.com/76855180/131389660-e40d5e6d-145f-48f3-aad4-c933f55b02f8.png)

Removed ``if`` statement:

![all commented](https://user-images.githubusercontent.com/76855180/131389695-e6c6a146-55c7-48d1-8a11-94b47f2a1547.png)

**Comment by AdisonCavani** [comment]
Previously I was using a AUR package, not compiling myself

**Comment by LinusDierheimer** [comment]
Hot guess, but replace the DRM line with a `puts("Would use DRM");`, leaving the if as is.

**Comment by AdisonCavani** [comment]
![replacement](https://user-images.githubusercontent.com/76855180/131390802-40056f20-d829-490f-8593-bdeee5f67ada.png)

**Comment by LinusDierheimer** [comment]
Does the error still occur with `fastfetch --set resolution=setval`?  If no, most probably the DE code is to blame.

**Comment by AdisonCavani** [comment]
![space](https://user-images.githubusercontent.com/76855180/131392414-dfdc9013-2788-4ea9-9dc9-251e731ce62e.png)

**Comment by LinusDierheimer** [comment]
Output of `fastfetch --set wm=setwm --set de=setde`?

**Comment by LinusDierheimer** [comment]
This means the error is in the WM / DE detection code, which sadly is used by half of the output, so we can't simple disable it part by part to find the issue. Best thing would be to use a debugger like gdb.

**Comment by AdisonCavani** [comment]
![args](https://user-images.githubusercontent.com/76855180/131392940-e2b8139d-d4ca-49a5-ae01-be11b4d1b3fd.png)

**Comment by LinusDierheimer** [comment]
Yea i forgot that wm and de is detected anyway, as things like theme, icons, font, etc depend on it.

**Comment by LinusDierheimer** [comment]
Inactive. Still be looking after it.
