### ISSUE TITLE
Fastfetch shows a GPU that is no longer connected

### ISSUE THREAD

**Issue by nocturn9x** [LinusDierheimer/fastfetch#84]
I'm not sure if it's a configuration issue, but fastfetch (and flashfetch) show my secondary RX 580 as present in the system while I'm pretty sure it's taking dust under my bed, while neofetch and lspci (correctly) don't mention it whatsoever. Is this maybe because of caching? How do I clear the cache if that's the case?

**Comment by LinusDierheimer** [comment]
`fastfetch --recache` Hope this helps. BTW `fastfetch --help` gives you an overview over available options. GPU is actually cached, as pci lookup is time expensive and i don't expect GPUs to change frequently, so this might actually be the issue.

**Comment by nocturn9x** [comment]
Deleting `.cache/fastfetch` actually did the trick, but also `--recache` works. Thanks!
