### ISSUE TITLE
WM not being detected

### ISSUE THREAD

**Issue by jiampong212** [LinusDierheimer/fastfetch#85]
![fastfetch](https://user-images.githubusercontent.com/75754198/130120968-a61890f8-1772-4a69-8c42-b0f13f36d42b.jpeg)
![flashfetch](https://user-images.githubusercontent.com/75754198/130120979-ffc223dc-d7ec-495f-a1db-f9ab624f236d.jpeg)

fastfetch and flashfetch not detecting bspwm. fastfetch have default config and i just removed lines from flashfetch.c

`~ > echo $XDG_CURRENT_DESKTOP
bspwm`

**Comment by LinusDierheimer** [comment]
What does `fastfetch --show-errors` output? I did a clean install of `bspwm` on my machine, which worked perfectly. However it did set `CURRENT_DESKTOP` and not `XDG_CURRENT_DESKTOP` like on your machine. Both should work tho.

**Comment by jiampong212** [comment]
![Screenshot-1632152552](https://user-images.githubusercontent.com/75754198/134031679-d8a3356c-6f89-48b5-bbf2-6caafdd1dabb.png)

i tried both building manually and installing the aur package.  both of them outputs this. wierd thing is that neofetch works

**Comment by LinusDierheimer** [comment]
Seems to be thinking that you are in a TTY session (obviously wrong). 
For WM / DE detection it first tests a lot of ENV variables, most notably
`XDG_CURRENT_DESKTOP`, `XDG_SESSION_DESKTOP`, `CURRENT_DESKTOP`, `SESSION_DESKTOP` and `DESKTOP_SESSION`, in the given order. If the first set value equals `TTY`, it skips WM / DE performance and outputs something like in your screenshot. Is it possible that applies to your machine? Try `env | sort | grep -i tty`.

**Comment by jiampong212** [comment]
fixed. for some reason, `XDG_SESSION_TYPE=tty` was set by default. I just added `export XDG_SESSION_TYPE=""` to zshenv and it worked. thank you
