### ISSUE TITLE
Build failing, glibconfig.h header file not found

### ISSUE THREAD

**Issue by jherzstein** [LinusDierheimer/fastfetch#88]
Trying to make the file and got this error:

`jordanh@debianP15s:~/fastfetch/build$ cmake --build .
[  1%] Building C object CMakeFiles/flashfetch.dir/src/common/settings.c.o
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/dconf/common/dconf-enums.h:23,
                 from /usr/include/dconf/dconf.h:23,
                 from /home/jordanh/fastfetch/src/common/settings.c:5:
/usr/include/glib-2.0/glib/gtypes.h:32:10: fatal error: glibconfig.h: No such file or directory
   32 | #include <glibconfig.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/flashfetch.dir/build.make:212: CMakeFiles/flashfetch.dir/src/common/settings.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/flashfetch.dir/all] Error 2
gmake: *** [Makefile:103: all] Error 2
`

I I'm using Debian, and I checked to make sure all of the dependencies were there, including libglib2.0-dev, so I'm not sure why this issue is occuring.

**Comment by LinusDierheimer** [comment]
Try `sudo ln -s /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h /usr/include/glib-2.0/`

**Comment by LinusDierheimer** [comment]
Closed because inactive. Reopen if it didn't work.
